/// <reference types="node" />

import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const tiktokers = [
  {
    handle: "dancequeen123",
    name: "Mauro Martínez",
    bio: "Amante del baile y la moda 💃✨",
    avatarUrl: "https://randomuser.me/api/portraits/men/1.jpg",
    profileUrl: "https://www.tiktok.com/@dancequeen123",
    country: "Uruguay",
    language: "es",
    niches: ["dance", "fashion"],
    followers: 150000,
    following: 200,
    totalLikes: 1200000,
    avgViews: 50000,
    avgLikes: 4000,
    avgComments: 300,
    engagementRate: 0.08,
    verified: false,
    contact: "mauromartinez@example.com",
    priceEst: 200,
    sampleVideos: { urls: ["https://tiktok.com/video/1", "https://tiktok.com/video/2"] },
    source: "manual_seed",
    lastScrapedAt: new Date(),
    raw: { platform: "tiktok" },
  },
  {
    handle: "techlover_mx",
    name: "Carlos Rivera",
    bio: "Reseñas de gadgets y tips de tecnología 🔌📱",
    avatarUrl: "https://randomuser.me/api/portraits/men/3.jpg",
    profileUrl: "https://www.tiktok.com/@techlover_mx",
    country: "Mexico",
    language: "es",
    niches: ["tech", "reviews"],
    followers: 95000,
    following: 180,
    totalLikes: 600000,
    avgViews: 30000,
    avgLikes: 2500,
    avgComments: 150,
    engagementRate: 0.10,
    verified: false,
    contact: "carlos@example.com",
    priceEst: 180,
    sampleVideos: { urls: ["https://tiktok.com/video/3"] },
    source: "manual_seed",
    lastScrapedAt: new Date(),
    raw: { platform: "tiktok" },
  },
  {
    handle: "cookwithlucas",
    name: "Lucas Torres",
    bio: "Recetas fáciles y deliciosas 🍝🍰",
    avatarUrl: "https://randomuser.me/api/portraits/men/4.jpg",
    profileUrl: "https://www.tiktok.com/@cookwithlucas",
    country: "Argentina",
    language: "es",
    niches: ["food", "lifestyle"],
    followers: 200000,
    following: 150,
    totalLikes: 1800000,
    avgViews: 80000,
    avgLikes: 6000,
    avgComments: 400,
    engagementRate: 0.12,
    verified: true,
    contact: "lucas@example.com",
    priceEst: 300,
    sampleVideos: { urls: ["https://tiktok.com/video/4", "https://tiktok.com/video/5"] },
    source: "manual_seed",
    lastScrapedAt: new Date(),
    raw: { platform: "tiktok" },
  },
  {
    handle: "fitnessleo",
    name: "Leo Fit",
    bio: "Entrenador personal 💪 Rutinas y motivación",
    avatarUrl: "https://randomuser.me/api/portraits/men/5.jpg",
    profileUrl: "https://www.tiktok.com/@fitnessleo",
    country: "Spain",
    language: "es",
    niches: ["fitness", "health"],
    followers: 175000,
    following: 220,
    totalLikes: 1400000,
    avgViews: 60000,
    avgLikes: 5000,
    avgComments: 350,
    engagementRate: 0.09,
    verified: false,
    contact: "leo@example.com",
    priceEst: 220,
    sampleVideos: { urls: ["https://tiktok.com/video/6"] },
    source: "manual_seed",
    lastScrapedAt: new Date(),
    raw: { platform: "tiktok" },
  },
  {
    handle: "travelwilson",
    name: "Wilson Johnson",
    bio: "Explorando el mundo 🌍✈️ Consejos de viajes",
    avatarUrl: "https://randomuser.me/api/portraits/men/6.jpg",
    profileUrl: "https://www.tiktok.com/@travelwilson",
    country: "USA",
    language: "en",
    niches: ["travel", "lifestyle"],
    followers: 320000,
    following: 300,
    totalLikes: 2500000,
    avgViews: 120000,
    avgLikes: 9500,
    avgComments: 600,
    engagementRate: 0.11,
    verified: true,
    contact: "wilson@example.com",
    priceEst: 500,
    sampleVideos: { urls: ["https://tiktok.com/video/7"] },
    source: "manual_seed",
    lastScrapedAt: new Date(),
    raw: { platform: "tiktok" },
  },
  {
    handle: "comedycarlos",
    name: "Carlos Comedy",
    bio: "Sketches cortos y humor absurdo 🤡",
    avatarUrl: "https://randomuser.me/api/portraits/men/7.jpg",
    profileUrl: "https://www.tiktok.com/@comedycarlos",
    country: "Colombia",
    language: "es",
    niches: ["comedy"],
    followers: 85000,
    following: 90,
    totalLikes: 420000,
    avgViews: 28000,
    avgLikes: 2200,
    avgComments: 180,
    engagementRate: 0.095,
    verified: false,
    contact: "comedycarlos@example.com",
    priceEst: 140,
    sampleVideos: { urls: ["https://tiktok.com/video/8"] },
    source: "manual_seed",
    lastScrapedAt: new Date(),
    raw: { platform: "tiktok" },
  },
  {
    handle: "gamer_nico",
    name: "Nicolás Game",
    bio: "Gameplays y clips épicos 🎮",
    avatarUrl: "https://randomuser.me/api/portraits/men/8.jpg",
    profileUrl: "https://www.tiktok.com/@gamer_nico",
    country: "Chile",
    language: "es",
    niches: ["gaming"],
    followers: 110000,
    following: 400,
    totalLikes: 800000,
    avgViews: 45000,
    avgLikes: 3500,
    avgComments: 210,
    engagementRate: 0.085,
    verified: false,
    contact: "nico@example.com",
    priceEst: 170,
    sampleVideos: { urls: ["https://tiktok.com/video/9"] },
    source: "manual_seed",
    lastScrapedAt: new Date(),
    raw: { platform: "tiktok" },
  },
  {
    handle: "beautybyana",
    name: "Ana B.",
    bio: "Makeup tutorials y reviews de productos 💄",
    avatarUrl: "https://randomuser.me/api/portraits/women/9.jpg",
    profileUrl: "https://www.tiktok.com/@beautybyana",
    country: "Peru",
    language: "es",
    niches: ["beauty", "fashion"],
    followers: 90000,
    following: 120,
    totalLikes: 550000,
    avgViews: 26000,
    avgLikes: 2100,
    avgComments: 140,
    engagementRate: 0.09,
    verified: false,
    contact: "beautyana@example.com",
    priceEst: 160,
    sampleVideos: { urls: ["https://tiktok.com/video/10"] },
    source: "manual_seed",
    lastScrapedAt: new Date(),
    raw: { platform: "tiktok" },
  },
  {
    handle: "musicmaria",
    name: "María Sonora",
    bio: "Covers y canciones originales 🎤",
    avatarUrl: "https://randomuser.me/api/portraits/women/10.jpg",
    profileUrl: "https://www.tiktok.com/@musicmaria",
    country: "Brazil",
    language: "pt",
    niches: ["music"],
    followers: 210000,
    following: 180,
    totalLikes: 1600000,
    avgViews: 70000,
    avgLikes: 5200,
    avgComments: 420,
    engagementRate: 0.10,
    verified: true,
    contact: "maria@example.com",
    priceEst: 320,
    sampleVideos: { urls: ["https://tiktok.com/video/11"] },
    source: "manual_seed",
    lastScrapedAt: new Date(),
    raw: { platform: "tiktok" },
  },
  {
    handle: "photookay",
    name: "Diego Foto",
    bio: "Fotografía móvil y edición 📸",
    avatarUrl: "https://randomuser.me/api/portraits/men/11.jpg",
    profileUrl: "https://www.tiktok.com/@photookay",
    country: "Ecuador",
    language: "es",
    niches: ["photography", "tech"],
    followers: 45000,
    following: 60,
    totalLikes: 180000,
    avgViews: 12000,
    avgLikes: 900,
    avgComments: 80,
    engagementRate: 0.07,
    verified: false,
    contact: "diego@example.com",
    priceEst: 90,
    sampleVideos: { urls: ["https://tiktok.com/video/12"] },
    source: "manual_seed",
    lastScrapedAt: new Date(),
    raw: { platform: "tiktok" },
  },
  {
    handle: "car_reviews_uy",
    name: "Pablo Auto",
    bio: "Reviews y comparativas de autos 🚗",
    avatarUrl: "https://randomuser.me/api/portraits/men/12.jpg",
    profileUrl: "https://www.tiktok.com/@car_reviews_uy",
    country: "Uruguay",
    language: "es",
    niches: ["cars", "reviews"],
    followers: 60000,
    following: 70,
    totalLikes: 300000,
    avgViews: 22000,
    avgLikes: 1600,
    avgComments: 120,
    engagementRate: 0.065,
    verified: false,
    contact: "pablo@example.com",
    priceEst: 130,
    sampleVideos: { urls: ["https://tiktok.com/video/13"] },
    source: "manual_seed",
    lastScrapedAt: new Date(),
    raw: { platform: "tiktok" },
  },
  {
    handle: "financeemma",
    name: "Emma Finance",
    bio: "Tips financieros simples para jóvenes 💸",
    avatarUrl: "https://randomuser.me/api/portraits/women/13.jpg",
    profileUrl: "https://www.tiktok.com/@financeemma",
    country: "UK",
    language: "en",
    niches: ["finance", "education"],
    followers: 72000,
    following: 90,
    totalLikes: 360000,
    avgViews: 28000,
    avgLikes: 2100,
    avgComments: 150,
    engagementRate: 0.08,
    verified: false,
    contact: "emma@example.com",
    priceEst: 175,
    sampleVideos: { urls: ["https://tiktok.com/video/14"] },
    source: "manual_seed",
    lastScrapedAt: new Date(),
    raw: { platform: "tiktok" },
  },
  {
    handle: "petloverlola",
    name: "Lola Pets",
    bio: "Perros, gatos y trucos para mascotas 🐶🐱",
    avatarUrl: "https://randomuser.me/api/portraits/women/14.jpg",
    profileUrl: "https://www.tiktok.com/@petloverlola",
    country: "Canada",
    language: "en",
    niches: ["pets", "lifestyle"],
    followers: 54000,
    following: 55,
    totalLikes: 250000,
    avgViews: 15000,
    avgLikes: 1200,
    avgComments: 90,
    engagementRate: 0.073,
    verified: false,
    contact: "lola@example.com",
    priceEst: 110,
    sampleVideos: { urls: ["https://tiktok.com/video/15"] },
    source: "manual_seed",
    lastScrapedAt: new Date(),
    raw: { platform: "tiktok" },
  },
  {
    handle: "sketchmania",
    name: "Laura Sketch",
    bio: "Sketches cortos y virales 🎭",
    avatarUrl: "https://randomuser.me/api/portraits/women/15.jpg",
    profileUrl: "https://www.tiktok.com/@sketchmania",
    country: "Dominican Republic",
    language: "es",
    niches: ["comedy", "sketch"],
    followers: 98000,
    following: 140,
    totalLikes: 610000,
    avgViews: 35000,
    avgLikes: 2600,
    avgComments: 200,
    engagementRate: 0.095,
    verified: false,
    contact: "laura@example.com",
    priceEst: 165,
    sampleVideos: { urls: ["https://tiktok.com/video/16"] },
    source: "manual_seed",
    lastScrapedAt: new Date(),
    raw: { platform: "tiktok" },
  },
  {
    handle: "streetartist",
    name: "Andrés Art",
    bio: "Arte urbano, timelapses y procesos 🎨",
    avatarUrl: "https://randomuser.me/api/portraits/men/16.jpg",
    profileUrl: "https://www.tiktok.com/@streetartist",
    country: "Paraguay",
    language: "es",
    niches: ["art", "photography"],
    followers: 30000,
    following: 40,
    totalLikes: 95000,
    avgViews: 7000,
    avgLikes: 600,
    avgComments: 40,
    engagementRate: 0.06,
    verified: false,
    contact: "andres@example.com",
    priceEst: 80,
    sampleVideos: { urls: ["https://tiktok.com/video/17"] },
    source: "manual_seed",
    lastScrapedAt: new Date(),
    raw: { platform: "tiktok" },
  },
  {
    handle: "yogawithsara",
    name: "Sara Yoga",
    bio: "Clases cortas de yoga y respiración 🧘‍♀️",
    avatarUrl: "https://randomuser.me/api/portraits/women/17.jpg",
    profileUrl: "https://www.tiktok.com/@yogawithsara",
    country: "Honduras",
    language: "es",
    niches: ["fitness", "wellness"],
    followers: 47000,
    following: 60,
    totalLikes: 200000,
    avgViews: 13000,
    avgLikes: 1000,
    avgComments: 70,
    engagementRate: 0.072,
    verified: false,
    contact: "sara@example.com",
    priceEst: 105,
    sampleVideos: { urls: ["https://tiktok.com/video/18"] },
    source: "manual_seed",
    lastScrapedAt: new Date(),
    raw: { platform: "tiktok" },
  },
  {
    handle: "streetfood_lee",
    name: "Lee Food",
    bio: "Descubriendo puestos callejeros y recetas rápidas",
    avatarUrl: "https://randomuser.me/api/portraits/men/18.jpg",
    profileUrl: "https://www.tiktok.com/@streetfood_lee",
    country: "Guatemala",
    language: "es",
    niches: ["food", "travel"],
    followers: 63000,
    following: 90,
    totalLikes: 320000,
    avgViews: 21000,
    avgLikes: 1700,
    avgComments: 110,
    engagementRate: 0.068,
    verified: false,
    contact: "lee@example.com",
    priceEst: 140,
    sampleVideos: { urls: ["https://tiktok.com/video/19"] },
    source: "manual_seed",
    lastScrapedAt: new Date(),
    raw: { platform: "tiktok" },
  },
  {
    handle: "diydonna",
    name: "Donna DIY",
    bio: "Proyectos DIY fáciles y económicos ✂️🧵",
    avatarUrl: "https://randomuser.me/api/portraits/women/19.jpg",
    profileUrl: "https://www.tiktok.com/@diydonna",
    country: "Puerto Rico",
    language: "es",
    niches: ["diy", "crafts"],
    followers: 41000,
    following: 50,
    totalLikes: 150000,
    avgViews: 11000,
    avgLikes: 900,
    avgComments: 60,
    engagementRate: 0.07,
    verified: false,
    contact: "donna@example.com",
    priceEst: 95,
    sampleVideos: { urls: ["https://tiktok.com/video/20"] },
    source: "manual_seed",
    lastScrapedAt: new Date(),
    raw: { platform: "tiktok" },
  }
];

async function main() {
  console.log("🌱 Seeding database...");

  // Limpio la colección (borra todos los tiktokers)
  await prisma.tiktoker.deleteMany();

  // Inserto por handle con upsert (evita duplicados)
  for (const tiktoker of tiktokers) {
    try {
      await prisma.tiktoker.upsert({
        where: { handle: tiktoker.handle },
        update: {}, // no cambiar si ya existe
        create: tiktoker as any,
      });
      console.log(`Inserted / upserted ${tiktoker.handle}`);
    } catch (err) {
      console.error(`Error inserting ${tiktoker.handle}:`, err);
    }
  }

  console.log("✅ Seed completado con éxito");
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
