/// <reference types="node" />

import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

  const tiktokers = [
    {
  "handle": "rafael_garcest",
  "profileUrl": "https://www.tiktok.com/@rafael_garcest",
  "followers": 26100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/rafael_garcest.jpeg",
  "niche": "crypto",
  "avgViews": 5214,
  "engagementRate": 1.4,
  "bio": "🤓 Actuaría(ITAM)\\n📊 Inversionista cripto\\n📈 Aprende la importancia de invertir",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T15:49:49.082Z"
},
  {
  "handle": "financieramente.yt",
  "profileUrl": "https://www.tiktok.com/@financieramente.yt",
  "followers": 13100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/financieramente.yt.jpeg",
  "niche": "crypto",
  "avgViews": 28553,
  "engagementRate": 7.41,
  "bio": "- Finanzas Personales📊\\n- Inversiones 💰\\n- Trading📈\\n- Criptos💲\\n🎥YouTube👇🏼",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T15:50:18.131Z"
},
  {
  "handle": "cryptoabis5",
  "profileUrl": "https://www.tiktok.com/@cryptoabis5",
  "followers": 45500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/cryptoabis5.jpeg",
  "niche": "crypto",
  "avgViews": 66085,
  "engagementRate": 5.15,
  "bio": "FOLLOW FOR CRYPTO UPDATES\\nDM FOR PAID PROMO\\nJOIN FREE TG @cryptoabis6\\nLink 👇",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T15:50:57.558Z"
},
  {
  "handle": "99accuracytrading",
  "profileUrl": "https://www.tiktok.com/@99accuracytrading",
  "followers": 20800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/99accuracytrading.jpeg",
  "niche": "crypto",
  "avgViews": 19402,
  "engagementRate": 1.47,
  "bio": "50\\u002F50 Profit & Loss ⚖️\\n99% Accurate Signals ✅\\nJoin Free WhatsApp Channel 📲\\n👇",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T15:51:31.953Z"
},
  {
  "handle": "luisfossatidrop",
  "profileUrl": "https://www.tiktok.com/@luisfossatidrop",
  "followers": 43000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/luisfossatidrop.jpeg",
  "niche": "crypto",
  "avgViews": 22346,
  "engagementRate": 1.11,
  "bio": "Te enseño a vender por internet sin experiencia en mi Instagram 🤝",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T15:54:17.260Z"
},
  {
  "handle": "calvindhillsclips2.0",
  "profileUrl": "https://www.tiktok.com/@calvindhillsclips2.0",
  "followers": 16000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/calvindhillsclips2.0.jpeg",
  "niche": "crypto",
  "avgViews": 5126,
  "engagementRate": 0.28,
  "bio": "Join my mentorship and coaching program .\\n       Email now for more info📥",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T15:55:29.676Z"
},
  {
  "handle": "rebelcrypto",
  "profileUrl": "https://www.tiktok.com/@rebelcrypto",
  "followers": 14500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/rebelcrypto.jpeg",
  "niche": "crypto",
  "avgViews": 1890,
  "engagementRate": 0.66,
  "bio": "🚨Daily Crypto Content & Market Alerts 🚨 \\n📈 Simple breakdowns, real-time calls 🚀 \\n👇🏾 Free Calls & Tools 👇🏾",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T15:56:03.992Z"
},
  {
  "handle": "tendenciacrypto",
  "profileUrl": "https://www.tiktok.com/@tendenciacrypto",
  "followers": 34400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/tendenciacrypto.jpeg",
  "niche": "crypto",
  "avgViews": 2846,
  "engagementRate": 0.69,
  "bio": "IG: tendenciacrypto_\\nTrading, criptos, stockmarket.\\nEducación financiera.",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T15:57:54.970Z"
},
  {
  "handle": "rafauskiv",
  "profileUrl": "https://www.tiktok.com/@rafauskiv",
  "followers": 57900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/rafauskiv.jpeg",
  "niche": "crypto",
  "avgViews": 36806,
  "engagementRate": 3.14,
  "bio": "Inversión, Trading y Finanzas\\nEl broker que uso es Quantfury\\n⬇️ Conoce más ⬇️",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T15:58:25.451Z"
},
  {
  "handle": "coin_guide",
  "profileUrl": "https://www.tiktok.com/@coin_guide",
  "followers": 72900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/coin_guide.jpeg",
  "niche": "crypto",
  "avgViews": 43101,
  "engagementRate": 5.09,
  "bio": "Crypto investor since 2017\\nThe link to The Rise Up Community is 👇",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T15:58:55.702Z"
},
  {
  "handle": "cryptopythonn",
  "profileUrl": "https://www.tiktok.com/@cryptopythonn",
  "followers": 26600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/cryptopythonn.jpeg",
  "niche": "crypto",
  "avgViews": 221763,
  "engagementRate": 57.17,
  "bio": "Making Money 🖥️💸\\n\\nNUNCA TE ESCRIBIRÉ PRIMERO\\n🚨🚨",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T15:59:27.103Z"
},
  {
  "handle": "jaywaveltrading",
  "profileUrl": "https://www.tiktok.com/@jaywaveltrading",
  "followers": 11300,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/jaywaveltrading.jpeg",
  "niche": "crypto",
  "avgViews": 11967,
  "engagementRate": 7.73,
  "bio": "🚨Daily Crypto Content & Market Alerts Simple\\n🚨Breakdown real-time calls🚀",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T16:00:22.226Z"
},
  {
  "handle": "profit_app",
  "profileUrl": "https://www.tiktok.com/@profit_app",
  "followers": 49000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/profit_app.jpeg",
  "niche": "crypto",
  "avgViews": 234497,
  "engagementRate": 14.27,
  "bio": "Get instant chart analysis.\\nSearch 👉 \\",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T16:00:50.594Z"
},
  {
  "handle": "fabianoguillentiktok",
  "profileUrl": "https://www.tiktok.com/@fabianoguillentiktok",
  "followers": 38300,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/fabianoguillentiktok.jpeg",
  "niche": "crypto",
  "avgViews": 25588,
  "engagementRate": 6.39,
  "bio": "• FABIANO   GUILLEN •\\nStand Up Comedy🇵🇦 Made in Braza 🇧🇷\\nShows ⤵️",
  "country": "por",
  "lastScrapedAt": "2025-09-14T16:02:09.239Z"
},
  {
  "handle": "agustinnicola.oficial",
  "profileUrl": "https://www.tiktok.com/@agustinnicola.oficial",
  "followers": 67700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/agustinnicola.oficial.jpeg",
  "niche": "crypto",
  "avgViews": 17405,
  "engagementRate": 1.29,
  "bio": "Te enseño a hacer 💲 con tu 📱\\nÚNICA CUENTA🚨\\nig: agustinnicola33",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T16:02:47.935Z"
},
  {
  "handle": "juanma.cripto",
  "profileUrl": "https://www.tiktok.com/@juanma.cripto",
  "followers": 16200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/juanma.cripto.jpeg",
  "niche": "crypto",
  "avgViews": 2491,
  "engagementRate": 0.82,
  "bio": "CRIPTO 📘 Autor del libro ABC Cripto \\u002F No contacto a Nadie⚠️ \\u002F Mis Redes 👇",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T16:03:17.998Z"
},
  {
  "handle": "full.saturn",
  "profileUrl": "https://www.tiktok.com/@full.saturn",
  "followers": 62100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/full.saturn.jpeg",
  "niche": "crypto",
  "avgViews": 33400,
  "engagementRate": 2.33,
  "bio": "CRYPTO & MÊMESCOINS 📈\\nNews, Stratégies & méthodes puissantes\\nAccès direct 👇",
  "country": "fra",
  "lastScrapedAt": "2025-09-14T16:03:53.297Z"
},
  {
  "handle": "toobit_toobeex",
  "profileUrl": "https://www.tiktok.com/@toobit_toobeex",
  "followers": 70900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/toobit_toobeex.jpeg",
  "niche": "crypto",
  "avgViews": 244090,
  "engagementRate": 12.06,
  "bio": "Hi,it's bee.Stay profit👇",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T16:04:22.435Z"
},
  {
  "handle": "blockchainbullh0rnalpha",
  "profileUrl": "https://www.tiktok.com/@blockchainbullh0rnalpha",
  "followers": 18000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/blockchainbullh0rnalpha.jpeg",
  "niche": "crypto",
  "avgViews": 3849,
  "engagementRate": 0.35,
  "bio": "Just a Middle Aged Man on TikTok! 😆",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T16:04:57.470Z"
},
  {
  "handle": "cryptomataa",
  "profileUrl": "https://www.tiktok.com/@cryptomataa",
  "followers": 10600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/cryptomataa.jpeg",
  "niche": "crypto",
  "avgViews": 6735,
  "engagementRate": 3.33,
  "bio": "IG: @cryptomata\\n \\n👇 Comunidad de WhatsApp 👇\\n          \\n   ⬇️YOUTUBE ⬇️",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T16:05:35.315Z"
},
  {
  "handle": "archivocripto",
  "profileUrl": "https://www.tiktok.com/@archivocripto",
  "followers": 48900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/archivocripto.jpeg",
  "niche": "crypto",
  "avgViews": 3065,
  "engagementRate": 0.28,
  "bio": "Aprende Sobre Criptomonedas Responsablente\\nÚnica cuenta. Jamás envío mensajes.",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T16:06:11.908Z"
},
  {
  "handle": "richroots.7",
  "profileUrl": "https://www.tiktok.com/@richroots.7",
  "followers": 12500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/richroots.7.jpeg",
  "niche": "crypto",
  "avgViews": 100307,
  "engagementRate": 19.02,
  "bio": "I am helping you with smart money moves, Finance tips about investing in crypto.",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T16:07:28.448Z"
},
  {
  "handle": "martin_trader",
  "profileUrl": "https://www.tiktok.com/@martin_trader",
  "followers": 57800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/martin_trader.jpeg",
  "niche": "crypto",
  "avgViews": 6544,
  "engagementRate": 0.5,
  "bio": "⚠️ Única cuenta Oficial ⚠️\\n\\n👇Todas mis redes sociales👇",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T16:08:13.909Z"
},
  {
  "handle": "monjetrading",
  "profileUrl": "https://www.tiktok.com/@monjetrading",
  "followers": 20000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/monjetrading.jpeg",
  "niche": "crypto",
  "avgViews": 388450,
  "engagementRate": 68.39,
  "bio": "🏆| Te ayudo a ser un inversor rentable \\n🧠| Estrategia personalizada 👇🏼",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T16:08:44.153Z"
},
  {
  "handle": "fersandovalpulice",
  "profileUrl": "https://www.tiktok.com/@fersandovalpulice",
  "followers": 55200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/fersandovalpulice.jpeg",
  "niche": "crypto",
  "avgViews": 2054062,
  "engagementRate": 454.01,
  "bio": "Inversiones, negocios 💰✨, la vida, viajes y just for fun 🫶🏼 @puntovekio 🎭",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T16:09:14.826Z"
},
  {
  "handle": "chadsartin.com033",
  "profileUrl": "https://www.tiktok.com/@chadsartin.com033",
  "followers": 10200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/chadsartin.com033.jpeg",
  "niche": "crypto",
  "avgViews": 442,
  "engagementRate": 0.17,
  "bio": "The new system is here make sure your wallet is connected with the web3 ☑️",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T16:10:10.851Z"
},
  {
  "handle": "skeyscrypto",
  "profileUrl": "https://www.tiktok.com/@skeyscrypto",
  "followers": 19800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/skeyscrypto.jpeg",
  "niche": "crypto",
  "avgViews": 8354,
  "engagementRate": 3.7,
  "bio": "God Above All\\n\\nFormerly Yaboyskey \\nSolnic leader \\nI teach regular Folks crypto",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T16:10:50.189Z"
},
  {
  "handle": "conratrades",
  "profileUrl": "https://www.tiktok.com/@conratrades",
  "followers": 39500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/conratrades.jpeg",
  "niche": "crypto",
  "avgViews": 9030,
  "engagementRate": 2.31,
  "bio": "day trader",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T16:11:46.068Z"
},
  {
  "handle": "buscandocryptodinero",
  "profileUrl": "https://www.tiktok.com/@buscandocryptodinero",
  "followers": 15100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/buscandocryptodinero.jpeg",
  "niche": "crypto",
  "avgViews": 6601,
  "engagementRate": 2.7,
  "bio": "Youtube 107k + Análisis Tecnico de Cryptos, altcoins, libros y Trading... links:",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T16:12:20.959Z"
},
  {
  "handle": "kingofcryptoofficial",
  "profileUrl": "https://www.tiktok.com/@kingofcryptoofficial",
  "followers": 23100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/kingofcryptoofficial.jpeg",
  "niche": "crypto",
  "avgViews": 21230,
  "engagementRate": 6.02,
  "bio": "FOR PERSONAL TRADE CONTACE ME\\nKINGS OFFICIAL\\n+923136057883",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T16:13:16.356Z"
},
  {
  "handle": "jjchagerbenbtc5",
  "profileUrl": "https://www.tiktok.com/@jjchagerbenbtc5",
  "followers": 40400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/jjchagerbenbtc5.jpeg",
  "niche": "crypto",
  "avgViews": 28626,
  "engagementRate": 3.58,
  "bio": "🔻☠️👁️Jubilado 35 años👁️☠️🔻\\nPetroleum Engineer\\nBitcoin\\n👇MENTORIA PREMIUM 👇",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T16:14:06.028Z"
},
  {
  "handle": "mitico.business",
  "profileUrl": "https://www.tiktok.com/@mitico.business",
  "followers": 54400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/mitico.business.jpeg",
  "niche": "crypto",
  "avgViews": 204672,
  "engagementRate": 18.53,
  "bio": "Negocios 🤝\\nInversiones 📈\\nCriptos 💎\\nCuenta Personal:\\n @mitico.ok",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T16:14:35.735Z"
},
  {
  "handle": "king_trader01",
  "profileUrl": "https://www.tiktok.com/@king_trader01",
  "followers": 32600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/king_trader01.jpeg",
  "niche": "crypto",
  "avgViews": 4848,
  "engagementRate": 0.76,
  "bio": "100% accurate Trading Signal's available\\n +447577317152\\n @King_tradar01 Telgrm",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T16:15:15.108Z"
},
  {
  "handle": "top_cryptos_666",
  "profileUrl": "https://www.tiktok.com/@top_cryptos_666",
  "followers": 11500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/top_cryptos_666.jpeg",
  "niche": "crypto",
  "avgViews": 64850,
  "engagementRate": 4.88,
  "bio": "I may overreact sometimes but i don't Promote scams ! next 1000X+ down below ↙️",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T16:15:43.465Z"
},
  {
  "handle": "tradezilla39",
  "profileUrl": "https://www.tiktok.com/@tradezilla39",
  "followers": 22400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/tradezilla39.jpeg",
  "niche": "crypto",
  "avgViews": 65785,
  "engagementRate": 17.58,
  "bio": "🔹 DAILY Dose of Trading 🔹\\n22k\\u002F23k",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T16:16:14.255Z"
},
  {
  "handle": "cryptoinsider_",
  "profileUrl": "https://www.tiktok.com/@cryptoinsider_",
  "followers": 12400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/cryptoinsider_.jpeg",
  "niche": "crypto",
  "avgViews": 30253,
  "engagementRate": 9.54,
  "bio": "💎 Follow to learn about crypto 💎\\n🤝 Free Discord 🤝\\n👇 ... & open in browser👇",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T16:16:45.320Z"
},
  {
  "handle": "cryptowewo_10",
  "profileUrl": "https://www.tiktok.com/@cryptowewo_10",
  "followers": 24900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/cryptowewo_10.jpeg",
  "niche": "crypto",
  "avgViews": 1692,
  "engagementRate": 0.16,
  "bio": "Payhip.com\\u002Fcryptowewo For my books\\nX:@cryptowewo_10",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T16:17:20.597Z"
},
  {
  "handle": "alaingode.oficial",
  "profileUrl": "https://www.tiktok.com/@alaingode.oficial",
  "followers": 38000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/alaingode.oficial.jpeg",
  "niche": "crypto",
  "avgViews": 47339,
  "engagementRate": 2.98,
  "bio": "⚠️NO TE VOY A ESCRIBIR PRIMERO⚠️\\n\\nTe enseño el mundo cripto en sencillo📈 | 1M",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T16:19:50.729Z"
},
  {
  "handle": "crashcoursecrypto.es",
  "profileUrl": "https://www.tiktok.com/@crashcoursecrypto.es",
  "followers": 18200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/crashcoursecrypto.es.jpeg",
  "niche": "crypto",
  "avgViews": 4358,
  "engagementRate": 0.95,
  "bio": "Noticias diarias sobre criptomonedas 📰\\n\\nMejores criptomonedas nuevas 🚀",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T16:20:31.201Z"
},
{
  "handle": "serenasrosess",
  "profileUrl": "https://www.tiktok.com/@serenasrosess",
  "followers": 34000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/serenasrosess.jpeg",
  "niche": "makeup",
  "avgViews": 130210,
  "engagementRate": 38.46,
  "bio": "📍🇺🇸 NYC\\n100k on instagram.\\nWeird but genius hacks🎀\\nMy only account",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T16:58:38.228Z"
},
  {
  "handle": "heartw0r3",
  "profileUrl": "https://www.tiktok.com/@heartw0r3",
  "followers": 31200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/heartw0r3.jpeg",
  "niche": "makeup",
  "avgViews": 7613,
  "engagementRate": 0.61,
  "bio": "💌: heartw0r3@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T16:59:05.748Z"
},
  {
  "handle": "ninetynine_dreams",
  "profileUrl": "https://www.tiktok.com/@ninetynine_dreams",
  "followers": 55000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/ninetynine_dreams.jpeg",
  "niche": "makeup",
  "avgViews": 22414,
  "engagementRate": 0.84,
  "bio": "🧚‍♀️Comfortable & Stylish Lashes🧚‍♀️\\n20% OFF Code: TikTok20\\n💗Shop Now⬇️",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T16:59:35.724Z"
},
  {
  "handle": "ikari.bby",
  "profileUrl": "https://www.tiktok.com/@ikari.bby",
  "followers": 70500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/ikari.bby.jpeg",
  "niche": "makeup",
  "avgViews": 899808,
  "engagementRate": 166.91,
  "bio": "ari not kari :)\\n🇯🇵🇬🇧\\nPr: ariatamagotchi@gmail.com\\n@pocari.art",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:00:21.187Z"
},
  {
  "handle": "figueluuu",
  "profileUrl": "https://www.tiktok.com/@figueluuu",
  "followers": 39100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/figueluuu.jpeg",
  "niche": "makeup",
  "avgViews": 611682,
  "engagementRate": 230.29,
  "bio": "🇺🇾",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T17:01:25.760Z"
},
  {
  "handle": "makeupbyparyss",
  "profileUrl": "https://www.tiktok.com/@makeupbyparyss",
  "followers": 72800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/makeupbyparyss.jpeg",
  "niche": "makeup",
  "avgViews": 6334,
  "engagementRate": 0.45,
  "bio": "Insta : makeupbyparyss\\n📍 Sydney, NSW",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:03:13.109Z"
},
  {
  "handle": "grungeangelz",
  "profileUrl": "https://www.tiktok.com/@grungeangelz",
  "followers": 46600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/grungeangelz.jpeg",
  "niche": "makeup",
  "avgViews": 37282,
  "engagementRate": 17.69,
  "bio": "network: +900k\\n@⛓️Grunge girls⛓️ \\n📩grungeeveraesth@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:03:54.039Z"
},
  {
  "handle": "jennita_7",
  "profileUrl": "https://www.tiktok.com/@jennita_7",
  "followers": 20300,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/jennita_7.jpeg",
  "niche": "makeup",
  "avgViews": 168439,
  "engagementRate": 54.74,
  "bio": "que onda mi gente bella💕\\nbienvenidos\\n🇦🇷🇧🇴",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T17:04:25.330Z"
},
  {
  "handle": "evellynnathlia",
  "profileUrl": "https://www.tiktok.com/@evellynnathlia",
  "followers": 17500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/evellynnathlia.jpeg",
  "niche": "makeup",
  "avgViews": 184349,
  "engagementRate": 145.92,
  "bio": "💜\\n💅🏻▪︎🧖🏻‍♀️▪︎💄",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T17:05:06.115Z"
},
  {
  "handle": "koshkina.star",
  "profileUrl": "https://www.tiktok.com/@koshkina.star",
  "followers": 28700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/koshkina.star.jpeg",
  "niche": "makeup",
  "avgViews": 733378,
  "engagementRate": 23.38,
  "bio": "",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:06:24.023Z"
},
  {
  "handle": "parastaennen",
  "profileUrl": "https://www.tiktok.com/@parastaennen",
  "followers": 24500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/parastaennen.jpeg",
  "niche": "makeup",
  "avgViews": 5556,
  "engagementRate": 1.35,
  "bio": "House wife. Mom. Finnish. That's me. And you can find here really bad humour.",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:07:07.285Z"
},
  {
  "handle": "soshebeauty",
  "profileUrl": "https://www.tiktok.com/@soshebeauty",
  "followers": 16500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/soshebeauty.jpeg",
  "niche": "makeup",
  "avgViews": 91391,
  "engagementRate": 5.92,
  "bio": "Expect more from your makeup™\\nDM us \\",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:09:39.248Z"
},
  {
  "handle": "hillymakeup",
  "profileUrl": "https://www.tiktok.com/@hillymakeup",
  "followers": 33600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/hillymakeup.jpeg",
  "niche": "makeup",
  "avgViews": 478617,
  "engagementRate": 122.17,
  "bio": "Maquilladora en Lima🇵🇪\\nServicio a domicilio✨🧚\\n📍Chorrillos \\nIg: hilly_makeup1",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T17:11:32.262Z"
},
  {
  "handle": "rosiegodwin",
  "profileUrl": "https://www.tiktok.com/@rosiegodwin",
  "followers": 65300,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/rosiegodwin.jpeg",
  "niche": "makeup",
  "avgViews": 919550,
  "engagementRate": 125.61,
  "bio": "✉️ teamrosie@yoofgroup.com\\n@myprotein @UKLASH DC: ROSIEGODWIN\\n@Fashion Nova",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:12:11.726Z"
},
  {
  "handle": "mariadmakeup",
  "profileUrl": "https://www.tiktok.com/@mariadmakeup",
  "followers": 18600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/mariadmakeup.jpeg",
  "niche": "makeup",
  "avgViews": 27618,
  "engagementRate": 13.08,
  "bio": "📍București | Ilfov\\n🌺MUA & TRAINER\\n💌maria_dinca_809@yahoo.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:12:53.777Z"
},
  {
  "handle": "kellyy.hdzz",
  "profileUrl": "https://www.tiktok.com/@kellyy.hdzz",
  "followers": 43000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/kellyy.hdzz.jpeg",
  "niche": "makeup",
  "avgViews": 318026,
  "engagementRate": 80.71,
  "bio": "💌 kellyhdz02@icloud.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:14:03.439Z"
},
  {
  "handle": "iiimane_",
  "profileUrl": "https://www.tiktok.com/@iiimane_",
  "followers": 71800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/iiimane_.jpeg",
  "niche": "makeup",
  "avgViews": 1437539,
  "engagementRate": 289.25,
  "bio": "🇲🇦\\nimane.im.pro@gmail.com\\nbased in france\\nig : iimaneee_",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:15:32.055Z"
},
  {
  "handle": "xnxhdb0",
  "profileUrl": "https://www.tiktok.com/@xnxhdb0",
  "followers": 11500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/xnxhdb0.jpeg",
  "niche": "makeup",
  "avgViews": 450,
  "engagementRate": 0.19,
  "bio": "",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:16:07.753Z"
},
  {
  "handle": ".ephxnyyl",
  "profileUrl": "https://www.tiktok.com/@.ephxnyyl",
  "followers": 63300,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/.ephxnyyl.jpeg",
  "niche": "makeup",
  "avgViews": 5955,
  "engagementRate": 1.49,
  "bio": "🦢🪞✨\\nMakeup ✧ 小红书 ✧ fashion!\\nYESSTYLE CODE: EPHXNYYL20\\n✉️: ephxnyyl@gmail.com\\nNL",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:16:47.413Z"
},
  {
  "handle": "maiatorres_",
  "profileUrl": "https://www.tiktok.com/@maiatorres_",
  "followers": 13200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/maiatorres_.jpeg",
  "niche": "makeup",
  "avgViews": 388867,
  "engagementRate": 282.39,
  "bio": "Mai Towers baby👄\\nmade in Arg🇦🇷\\nIg: _maiatorress",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T17:18:07.505Z"
},
  {
  "handle": "bareminerals",
  "profileUrl": "https://www.tiktok.com/@bareminerals",
  "followers": 42800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/bareminerals.jpeg",
  "niche": "makeup",
  "avgViews": 1095,
  "engagementRate": 0.09,
  "bio": "Makeup and skincare designed to give you better bare skin every day.",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:19:00.100Z"
},
  {
  "handle": "arleetter_",
  "profileUrl": "https://www.tiktok.com/@arleetter_",
  "followers": 76900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/arleetter_.jpeg",
  "niche": "makeup",
  "avgViews": 9248,
  "engagementRate": 0.69,
  "bio": "Makeup | Grwm | Minivlog",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T17:19:48.830Z"
},
  {
  "handle": "virg0girl777",
  "profileUrl": "https://www.tiktok.com/@virg0girl777",
  "followers": 47500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/virg0girl777.jpeg",
  "niche": "makeup",
  "avgViews": 216815,
  "engagementRate": 107.31,
  "bio": "23.\\nSpotify - bethany amy",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:20:24.508Z"
},
  {
  "handle": "y2kqwe0r",
  "profileUrl": "https://www.tiktok.com/@y2kqwe0r",
  "followers": 41800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/y2kqwe0r.jpeg",
  "niche": "makeup",
  "avgViews": 798350,
  "engagementRate": 56.5,
  "bio": "spam like = Block & Report🫶\\nthank you all for 31.2k followers",
  "country": "eng<",
  "lastScrapedAt": "2025-09-14T17:21:01.135Z"
},
  {
  "handle": "notbeila",
  "profileUrl": "https://www.tiktok.com/@notbeila",
  "followers": 19100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/notbeila.jpeg",
  "niche": "makeup",
  "avgViews": 1161600,
  "engagementRate": 748.68,
  "bio": "dominanter\\n🤎💼☕️👡🧉",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:21:49.407Z"
},
  {
  "handle": "user419600253",
  "profileUrl": "https://www.tiktok.com/@user419600253",
  "followers": 11400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/user419600253.jpeg",
  "niche": "makeup",
  "avgViews": 90187,
  "engagementRate": 2.92,
  "bio": "",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:22:48.366Z"
},
  {
  "handle": "maelleclm_",
  "profileUrl": "https://www.tiktok.com/@maelleclm_",
  "followers": 10200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/maelleclm_.jpeg",
  "niche": "makeup",
  "avgViews": 27954,
  "engagementRate": 73.26,
  "bio": "🌚",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:23:41.284Z"
},
  {
  "handle": "leilasmakeupstudio",
  "profileUrl": "https://www.tiktok.com/@leilasmakeupstudio",
  "followers": 23100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/leilasmakeupstudio.jpeg",
  "niche": "makeup",
  "avgViews": 65650,
  "engagementRate": 23.81,
  "bio": "Bridal & Event Makeup Artist\\nAll Bookings | Via Link Below  ↴\\nPunchbowl, NSW",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:24:10.625Z"
},
  {
  "handle": "fernanndadi",
  "profileUrl": "https://www.tiktok.com/@fernanndadi",
  "followers": 72000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/fernanndadi.jpeg",
  "niche": "makeup",
  "avgViews": 213150,
  "engagementRate": 34.42,
  "bio": "Ig:@fernanndadimakeup\\nMTY MAKEUP ARTIST🌟",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:24:46.425Z"
},
{
  "handle": "jaxon.techhh",
  "profileUrl": "https://www.tiktok.com/@jaxon.techhh",
  "followers": 12500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/jaxon.techhh.jpeg",
  "niche": "tech",
  "avgViews": 7623,
  "engagementRate": 8.32,
  "bio": "✉️ jaxon.techhh@gmail.com\\n\\nCode \\",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:31:43.015Z"
},
  {
  "handle": "herbsterz",
  "profileUrl": "https://www.tiktok.com/@herbsterz",
  "followers": 10700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/herbsterz.jpeg",
  "niche": "tech",
  "avgViews": 103276,
  "engagementRate": 10.4,
  "bio": "📧 Herbsterzbiz@gmail.com 📧\\nUse code \\",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:32:46.422Z"
},
  {
  "handle": "aqua_tech_",
  "profileUrl": "https://www.tiktok.com/@aqua_tech_",
  "followers": 29700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/aqua_tech_.jpeg",
  "niche": "tech",
  "avgViews": 72566,
  "engagementRate": 25.66,
  "bio": "14 | 🇳🇴\\n-\\nLink in @aqua.tech.'s bio\\n-\\n📧: aqua.tech.tiktok@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:33:42.377Z"
},
  {
  "handle": "tech.vibesz",
  "profileUrl": "https://www.tiktok.com/@tech.vibesz",
  "followers": 24800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/tech.vibesz.jpeg",
  "niche": "tech",
  "avgViews": 54107,
  "engagementRate": 18.36,
  "bio": "Spam account @vibesz \\n📩3amvibez.Tech@gmail.com\\nEverything in beacon⬇️",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:34:12.368Z"
},
  {
  "handle": "2dros",
  "profileUrl": "https://www.tiktok.com/@2dros",
  "followers": 16000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/2dros.jpeg",
  "niche": "tech",
  "avgViews": 22181,
  "engagementRate": 18.66,
  "bio": "Peripheral enjoyer",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:34:59.626Z"
},
  {
  "handle": "izayoaa",
  "profileUrl": "https://www.tiktok.com/@izayoaa",
  "followers": 56700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/izayoaa.jpeg",
  "niche": "tech",
  "avgViews": 5080,
  "engagementRate": 1.12,
  "bio": "🇫🇷 French Tech Creator 🇫🇷\\n👀 Looking for sponsors 👀\\n✉️izayoaa@gmail.com✉️",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:35:34.080Z"
},
  {
  "handle": "tecsant",
  "profileUrl": "https://www.tiktok.com/@tecsant",
  "followers": 26300,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/tecsant.jpeg",
  "niche": "tech",
  "avgViews": 18718,
  "engagementRate": 8.08,
  "bio": "Sponsor: marvincollabs@gmail.com 📩\\nReviews e Unboxing 🎬",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:36:05.000Z"
},
  {
  "handle": "its_delvis",
  "profileUrl": "https://www.tiktok.com/@its_delvis",
  "followers": 52900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/its_delvis.jpeg",
  "niche": "tech",
  "avgViews": 403073,
  "engagementRate": 70.06,
  "bio": "Welcome to my TechZone🚀\\n\\",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:36:36.379Z"
},
  {
  "handle": "darsh.zhh",
  "profileUrl": "https://www.tiktok.com/@darsh.zhh",
  "followers": 20900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/darsh.zhh.jpeg",
  "niche": "tech",
  "avgViews": 437867,
  "engagementRate": 195.98,
  "bio": "Sponsor: snipedarsh@gmail.com\\n7z esports 🇨🇭",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:38:19.569Z"
},
  {
  "handle": "cellopcs",
  "profileUrl": "https://www.tiktok.com/@cellopcs",
  "followers": 15500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/cellopcs.jpeg",
  "niche": "tech",
  "avgViews": 43081,
  "engagementRate": 17.86,
  "bio": "✅ cellobusinessdeals@gmail.com ✅",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:38:57.754Z"
},
  {
  "handle": "soymelya_",
  "profileUrl": "https://www.tiktok.com/@soymelya_",
  "followers": 52200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/soymelya_.jpeg",
  "niche": "tech",
  "avgViews": 64292,
  "engagementRate": 13.13,
  "bio": "Unboxing, tech, gaming, keebs\\n💌 melyatsg@gmail.com\\nIg\\u002FYt: soymelya_\\nLinks ↓",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:39:37.427Z"
},
  {
  "handle": "neiron_phone",
  "profileUrl": "https://www.tiktok.com/@neiron_phone",
  "followers": 39700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/neiron_phone.jpeg",
  "niche": "tech",
  "avgViews": 861767,
  "engagementRate": 172.84,
  "bio": "𝙑𝙞𝙙𝙚𝙤 𝙬𝙞𝙩𝙝 𝙋𝙝𝙤𝙣𝙚𝙨\\n🫸🏻Едітии🫷🏻\\n𝙎𝙐𝘽𝙎𝘾𝙍𝙄𝘽𝙀",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:40:29.109Z"
},
  {
  "handle": "euigoti",
  "profileUrl": "https://www.tiktok.com/@euigoti",
  "followers": 17500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/euigoti.jpeg",
  "niche": "tech",
  "avgViews": 0,
  "engagementRate": 0,
  "bio": "✉️ euigoti@gmail.com\\n🔗 Important links and my wallpapers 👇🏻",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:40:55.936Z"
},
  {
  "handle": "pulsetechh",
  "profileUrl": "https://www.tiktok.com/@pulsetechh",
  "followers": 10400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/pulsetechh.jpeg",
  "niche": "tech",
  "avgViews": 125740,
  "engagementRate": 93.17,
  "bio": "Welcome to my channel 👋🏼\\n-setup\\u002Froom\\n-2 day upload \\n🌿All links & products👇🏼",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:41:47.152Z"
},
  {
  "handle": "nexstay",
  "profileUrl": "https://www.tiktok.com/@nexstay",
  "followers": 22200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/nexstay.jpeg",
  "niche": "tech",
  "avgViews": 27029,
  "engagementRate": 4.51,
  "bio": "@SYLON \\nnexstaycollab@gmail.com 📥",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:42:18.382Z"
},
  {
  "handle": "huawei.kz1",
  "profileUrl": "https://www.tiktok.com/@huawei.kz1",
  "followers": 28800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/huawei.kz1.jpeg",
  "niche": "tech",
  "avgViews": 6279,
  "engagementRate": 1.58,
  "bio": "Kabykenov S\\nThe telegram channel is at the bottom of the link\\n👇🏻👇🏻👇🏻",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:43:04.434Z"
},
  {
  "handle": "mans.setup",
  "profileUrl": "https://www.tiktok.com/@mans.setup",
  "followers": 15500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/mans.setup.jpeg",
  "niche": "tech",
  "avgViews": 4202,
  "engagementRate": 2.67,
  "bio": "Best Brazilian techtoker🇧🇷\\nCollab📧\\nmansurenzo7@gmail.com",
  "country": "por",
  "lastScrapedAt": "2025-09-14T17:43:58.502Z"
},
  {
  "handle": "mashstatic",
  "profileUrl": "https://www.tiktok.com/@mashstatic",
  "followers": 46600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/mashstatic.jpeg",
  "niche": "tech",
  "avgViews": 9155,
  "engagementRate": 1.39,
  "bio": "Founder @Verfyd \\nTech, Life & everything in between\\nmashstatic@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:45:20.934Z"
},
  {
  "handle": "dudstech",
  "profileUrl": "https://www.tiktok.com/@dudstech",
  "followers": 14100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/dudstech.jpeg",
  "niche": "tech",
  "avgViews": 1388283,
  "engagementRate": 480.78,
  "bio": "",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:46:34.802Z"
},
  {
  "handle": ".s24_hype",
  "profileUrl": "https://www.tiktok.com/@.s24_hype",
  "followers": 21800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/.s24_hype.jpeg",
  "niche": "tech",
  "avgViews": 661517,
  "engagementRate": 212.97,
  "bio": "Thx for yall Support! 🫶\\nChrist is King ✝️",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:47:24.106Z"
},
  {
  "handle": "msr_clok",
  "profileUrl": "https://www.tiktok.com/@msr_clok",
  "followers": 29400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/msr_clok.jpeg",
  "niche": "tech",
  "avgViews": 1006239,
  "engagementRate": 41.49,
  "bio": "MSR'OPÇÕES\\nsiga no Instagram 👇\\n@ msr_clok",
  "country": "por",
  "lastScrapedAt": "2025-09-14T17:48:10.421Z"
},
  {
  "handle": "abood.tech1",
  "profileUrl": "https://www.tiktok.com/@abood.tech1",
  "followers": 27700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/abood.tech1.jpeg",
  "niche": "tech",
  "avgViews": 72148,
  "engagementRate": 19.89,
  "bio": "I'll help u improve ur setup 🙏 \\n\\n📩: business@abood-tech.com\\nSetup & PC 👇",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:48:53.848Z"
},
  {
  "handle": "techsosna",
  "profileUrl": "https://www.tiktok.com/@techsosna",
  "followers": 10600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/techsosna.jpeg",
  "niche": "tech",
  "avgViews": 888019,
  "engagementRate": 316.66,
  "bio": "pc setup \\u002F room\\n✉️: sosnabusiness0@gmail.com\\n⬇️ links⬇️",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:50:07.230Z"
},
  {
  "handle": "ntx.tech",
  "profileUrl": "https://www.tiktok.com/@ntx.tech",
  "followers": 16800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/ntx.tech.jpeg",
  "niche": "tech",
  "avgViews": 18122,
  "engagementRate": 6.78,
  "bio": "💻 setup • tech\\n✉️ ntxtechcontact@gmail.com\\n📨 DM for collab",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:50:59.924Z"
},
  {
  "handle": "slm_tech",
  "profileUrl": "https://www.tiktok.com/@slm_tech",
  "followers": 22200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/slm_tech.jpeg",
  "niche": "tech",
  "avgViews": 225527,
  "engagementRate": 55.16,
  "bio": "🎥| tech content creator |🎥\\nLooking for sponsors👀\\n✉️simtechtiktok@gmail.com✉️",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:51:42.587Z"
},
  {
  "handle": "knots.setup",
  "profileUrl": "https://www.tiktok.com/@knots.setup",
  "followers": 44000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/knots.setup.jpeg",
  "niche": "tech",
  "avgViews": 148027,
  "engagementRate": 26.23,
  "bio": "Window setup guy\\ncode \\",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:53:25.252Z"
},
  {
  "handle": "ricksetup",
  "profileUrl": "https://www.tiktok.com/@ricksetup",
  "followers": 30800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/ricksetup.jpeg",
  "niche": "tech",
  "avgViews": 5212,
  "engagementRate": 1.88,
  "bio": "peripherals enjoyer\\n📩 contact.ricksetup@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:53:58.029Z"
},
  {
  "handle": "s23hypeee",
  "profileUrl": "https://www.tiktok.com/@s23hypeee",
  "followers": 16400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/s23hypeee.jpeg",
  "niche": "tech",
  "avgViews": 1038267,
  "engagementRate": 451.74,
  "bio": "🇧🇷S23\\n🤝🏻: @S24_Hype @LUMEXTech™ @s23 Tech @Samy🇨🇦(S24_Hype) @S23 Tech",
  "country": "por",
  "lastScrapedAt": "2025-09-14T17:54:38.679Z"
},
  {
  "handle": "guuhsetup",
  "profileUrl": "https://www.tiktok.com/@guuhsetup",
  "followers": 12400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/guuhsetup.jpeg",
  "niche": "tech",
  "avgViews": 16035,
  "engagementRate": 13.84,
  "bio": "Setup | Tech\\n\\n📩 collab.guuhtech@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:55:14.898Z"
},
  {
  "handle": "liv.tech",
  "profileUrl": "https://www.tiktok.com/@liv.tech",
  "followers": 62500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/liv.tech.jpeg",
  "niche": "tech",
  "avgViews": 11513,
  "engagementRate": 2.82,
  "bio": "CODE \\",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:56:11.990Z"
},
  {
  "handle": "_oriontech",
  "profileUrl": "https://www.tiktok.com/@_oriontech",
  "followers": 11600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/_oriontech.jpeg",
  "niche": "tech",
  "avgViews": 1937357,
  "engagementRate": 2476.81,
  "bio": "",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:56:55.712Z"
},
  {
  "handle": "techwyuanfu",
  "profileUrl": "https://www.tiktok.com/@techwyuanfu",
  "followers": 40900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/techwyuanfu.jpeg",
  "niche": "tech",
  "avgViews": 1927463,
  "engagementRate": 368.39,
  "bio": "📱High-Quality Tech Content\\n📧techwyuanfu.business01@gmail.com\\n🫂Noldi\\nTemp Quit",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:57:45.618Z"
},
  {
  "handle": "brizzestp",
  "profileUrl": "https://www.tiktok.com/@brizzestp",
  "followers": 41800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/brizzestp.jpeg",
  "niche": "tech",
  "avgViews": 42897,
  "engagementRate": 7.83,
  "bio": "•Setup\\u002FJogos\\u002FTecnologia🖥️🇧🇷\\n•DM for collab📩\\n•Segue aí 🤍\\n•Links ⬇️",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T17:58:23.336Z"
},
  {
  "handle": "vhenri_tech",
  "profileUrl": "https://www.tiktok.com/@vhenri_tech",
  "followers": 15600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/vhenri_tech.jpeg",
  "niche": "tech",
  "avgViews": 98735,
  "engagementRate": 101.24,
  "bio": "Setup | Unboxing \\n   BR Tech🇧🇷\\n📩 henritech.collab@gmail.com\\n    ⬇️LINKS⬇️",
  "country": "por",
  "lastScrapedAt": "2025-09-14T17:59:00.672Z"
},
  {
  "handle": "byexosi",
  "profileUrl": "https://www.tiktok.com/@byexosi",
  "followers": 12200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/byexosi.jpeg",
  "niche": "tech",
  "avgViews": 214405,
  "engagementRate": 112.88,
  "bio": "Code \\",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T17:59:41.533Z"
},
  {
  "handle": ".ruanx",
  "profileUrl": "https://www.tiktok.com/@.ruanx",
  "followers": 15500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/.ruanx.jpeg",
  "niche": "tech",
  "avgViews": 1348,
  "engagementRate": 1.21,
  "bio": "just an admirer of peripherals\\n\\n📩 ruansenaaz@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T18:00:16.094Z"
},
  {
  "handle": "cryptixz7",
  "profileUrl": "https://www.tiktok.com/@cryptixz7",
  "followers": 10200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/cryptixz7.jpeg",
  "niche": "tech",
  "avgViews": 66651,
  "engagementRate": 131.37,
  "bio": "🌊10.2k\\u002F15k🌊\\nInstagram: EDITZ.BYGHOST (15.4k)\\nGT7 editor\\nCapCut",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T18:01:35.634Z"
},
  {
  "handle": "vieira74_",
  "profileUrl": "https://www.tiktok.com/@vieira74_",
  "followers": 11900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/vieira74_.jpeg",
  "niche": "tech",
  "avgViews": 13383,
  "engagementRate": 16.83,
  "bio": "Link das peças do pc 👇🏽",
  "country": "por",
  "lastScrapedAt": "2025-09-14T18:02:20.343Z"
},
  {
  "handle": "blakk.tech",
  "profileUrl": "https://www.tiktok.com/@blakk.tech",
  "followers": 71700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/blakk.tech.jpeg",
  "niche": "tech",
  "avgViews": 272083,
  "engagementRate": 31.65,
  "bio": "Setup Content Creator\\n✉️Contacto: blakktech09@gmail.com",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T18:03:06.750Z"
},
  {
  "handle": "kuush.tech",
  "profileUrl": "https://www.tiktok.com/@kuush.tech",
  "followers": 21400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/kuush.tech.jpeg",
  "niche": "tech",
  "avgViews": 812772,
  "engagementRate": 406.49,
  "bio": "✉️ kuushcontact@gmail.com\\n📂 Tech Reviewer\\n📨 DM for collab\\n⬇️ Links",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T18:04:46.295Z"
},
  {
  "handle": "raqz62",
  "profileUrl": "https://www.tiktok.com/@raqz62",
  "followers": 16700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/raqz62.jpeg",
  "niche": "tech",
  "avgViews": 145630,
  "engagementRate": 109.07,
  "bio": "✧ CONTENT CREATOR ✧ 🎥\\n Business Inquiries \\n📩RaqzTech@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T18:05:36.655Z"
},
  {
  "handle": "joaoitech",
  "profileUrl": "https://www.tiktok.com/@joaoitech",
  "followers": 19900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/joaoitech.jpeg",
  "niche": "tech",
  "avgViews": 89700,
  "engagementRate": 35.35,
  "bio": "Collab 📩\\njoaoinaciops04@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T18:06:28.878Z"
},
  {
  "handle": "losxytech",
  "profileUrl": "https://www.tiktok.com/@losxytech",
  "followers": 15200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/losxytech.jpeg",
  "niche": "tech",
  "avgViews": 3835,
  "engagementRate": 4.75,
  "bio": "Code \\",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T18:07:07.278Z"
},
  {
  "handle": "kirbyoui",
  "profileUrl": "https://www.tiktok.com/@kirbyoui",
  "followers": 16000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/kirbyoui.jpeg",
  "niche": "tech",
  "avgViews": 25216,
  "engagementRate": 28.87,
  "bio": "🇳🇴\\n⌨️Tech enjoyer📸\\n👀collaborations⤵️\\n📨kirbyoui@proton.me📨\\n⬇️Wallpapers⬇️",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T18:08:21.450Z"
},
  {
  "handle": "tech_antoo",
  "profileUrl": "https://www.tiktok.com/@tech_antoo",
  "followers": 24500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/tech_antoo.jpeg",
  "niche": "tech",
  "avgViews": 50895,
  "engagementRate": 29.35,
  "bio": "17 | 🇨🇦\\n⬇️Collaboration⬇️\\n📧techanto80@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T18:08:53.467Z"
},
  {
  "handle": ".wemzz",
  "profileUrl": "https://www.tiktok.com/@.wemzz",
  "followers": 10500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/.wemzz.jpeg",
  "niche": "tech",
  "avgViews": 117201,
  "engagementRate": 93.07,
  "bio": "Amen ✝️🇻🇦\\nCode \\",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T18:09:27.949Z"
},
  {
  "handle": "anysetup",
  "profileUrl": "https://www.tiktok.com/@anysetup",
  "followers": 17400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/anysetup.jpeg",
  "niche": "tech",
  "avgViews": 374333,
  "engagementRate": 196.28,
  "bio": "code ANYSETUP at Wallhack.com \\n\\n📩 anysetups@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T18:10:05.048Z"
},
  {
  "handle": ".prah",
  "profileUrl": "https://www.tiktok.com/@.prah",
  "followers": 16800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/.prah.jpeg",
  "niche": "tech",
  "avgViews": 2312,
  "engagementRate": 1.48,
  "bio": "Content Creator\\nBusiness Email: \\nprah@iflytalent.com\\n(prev. duhprah@gmail.com)",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T18:10:43.655Z"
},
{
  "handle": "maatilde.farfan",
  "profileUrl": "https://www.tiktok.com/@maatilde.farfan",
  "followers": 42000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/maatilde.farfan.jpeg",
  "niche": "fashion",
  "avgViews": 187032,
  "engagementRate": 45.83,
  "bio": "subo outfits\\n📥 maatilde.farfan@gmail.com",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T22:33:18.827Z"
},
  {
  "handle": "vintageyordy",
  "profileUrl": "https://www.tiktok.com/@vintageyordy",
  "followers": 22400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/vintageyordy.jpeg",
  "niche": "fashion",
  "avgViews": 6796,
  "engagementRate": 0.44,
  "bio": "DESIGN MEETS ETERNITY \\n\\n         EST 2018 ©️\\n\\nSHOP OUR PIECES 👇🏼",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T22:35:06.962Z"
},
  {
  "handle": "gelafindss",
  "profileUrl": "https://www.tiktok.com/@gelafindss",
  "followers": 10500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/gelafindss.jpeg",
  "niche": "fashion",
  "avgViews": 2142368,
  "engagementRate": 350.02,
  "bio": "OPEN FOR COLLABS! (just dm me!)\\nManifesting more sales to come! 🤞🏻✨\\n🧿🧿🧿",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T22:36:37.393Z"
},
  {
  "handle": "lucianaluis24",
  "profileUrl": "https://www.tiktok.com/@lucianaluis24",
  "followers": 21100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/lucianaluis24.jpeg",
  "niche": "fashion",
  "avgViews": 42242,
  "engagementRate": 40.17,
  "bio": "⛓️fashion content, o algo así\\nig: _lucianaluis",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T22:38:58.061Z"
},
  {
  "handle": "macaduraan",
  "profileUrl": "https://www.tiktok.com/@macaduraan",
  "followers": 33800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/macaduraan.jpeg",
  "niche": "fashion",
  "avgViews": 10016,
  "engagementRate": 1.25,
  "bio": "INSTAGRAM: @macaduraan\\n• 28 años • Chile • \\nSubo mis outfits 🩷",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T22:43:03.510Z"
},
  {
  "handle": "lucy_edwards7",
  "profileUrl": "https://www.tiktok.com/@lucy_edwards7",
  "followers": 23900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/lucy_edwards7.jpeg",
  "niche": "fashion",
  "avgViews": 540745,
  "engagementRate": 28.22,
  "bio": "Made in Chicago \\nModel: Black & Puerto Rican",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T22:44:47.142Z"
},
  {
  "handle": "c0nyblue",
  "profileUrl": "https://www.tiktok.com/@c0nyblue",
  "followers": 11500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/c0nyblue.jpeg",
  "niche": "fashion",
  "avgViews": 51498,
  "engagementRate": 91.26,
  "bio": "aquí tú fashion bestie 💗\\nig: c0nyblue",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T22:46:02.777Z"
},
  {
  "handle": "itsmartasolerr",
  "profileUrl": "https://www.tiktok.com/@itsmartasolerr",
  "followers": 59500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/itsmartasolerr.jpeg",
  "niche": "fashion",
  "avgViews": 531850,
  "engagementRate": 55.97,
  "bio": "Marta\\n@itsmartasoler\\n\\nmartasoler@agenciaolympia.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T22:47:33.613Z"
},
  {
  "handle": "tummycontroldress",
  "profileUrl": "https://www.tiktok.com/@tummycontroldress",
  "followers": 31100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/tummycontroldress.jpeg",
  "niche": "fashion",
  "avgViews": 700299,
  "engagementRate": 19.71,
  "bio": "Buy Now 🛍️👇👇",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T22:48:57.679Z"
},
  {
  "handle": "ea_sheinn",
  "profileUrl": "https://www.tiktok.com/@ea_sheinn",
  "followers": 23800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/ea_sheinn.jpeg",
  "niche": "fashion",
  "avgViews": 21289,
  "engagementRate": 10.28,
  "bio": "✨ Achadinhos \\n🩷 looks , promoção, moda",
  "country": "por",
  "lastScrapedAt": "2025-09-14T22:56:26.786Z"
},
  {
  "handle": "ariiixz_z",
  "profileUrl": "https://www.tiktok.com/@ariiixz_z",
  "followers": 28500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/ariiixz_z.jpeg",
  "niche": "fashion",
  "avgViews": 660004,
  "engagementRate": 415.43,
  "bio": "18🦭\\nLibra \\u002F 🇵🇪\\nIg: \\",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T22:58:00.896Z"
},
  {
  "handle": "magdalanaa",
  "profileUrl": "https://www.tiktok.com/@magdalanaa",
  "followers": 13900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/magdalanaa.jpeg",
  "niche": "fashion",
  "avgViews": 254955,
  "engagementRate": 302.43,
  "bio": "~💗~\\nig: magdalanaaa",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T22:59:48.775Z"
},
  {
  "handle": "ceren_dnzl",
  "profileUrl": "https://www.tiktok.com/@ceren_dnzl",
  "followers": 61400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/ceren_dnzl.jpeg",
  "niche": "fashion",
  "avgViews": 3683,
  "engagementRate": 0.68,
  "bio": "💌: cerendnzl20@gmail.com\\nIg: ceren_dnzl\\nDm for Cooperation\\n@best_clothesss",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T23:01:04.944Z"
},
  {
  "handle": "misscinyaethetics",
  "profileUrl": "https://www.tiktok.com/@misscinyaethetics",
  "followers": 52500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/misscinyaethetics.jpeg",
  "niche": "fashion",
  "avgViews": 4736,
  "engagementRate": 0.36,
  "bio": "Both dress and skincare posted here are available dm +2349137196669\\nIN FOR PROMO",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T23:04:24.464Z"
},
  {
  "handle": "tellmeleslie",
  "profileUrl": "https://www.tiktok.com/@tellmeleslie",
  "followers": 53600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/tellmeleslie.jpeg",
  "niche": "fashion",
  "avgViews": 138333,
  "engagementRate": 37.2,
  "bio": "creadora de contenido⭐️\\ncollabs📩: tellmelesliehb@gmail.com",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T23:05:38.354Z"
},
  {
  "handle": "ur_mamacitaxx",
  "profileUrl": "https://www.tiktok.com/@ur_mamacitaxx",
  "followers": 22500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/ur_mamacitaxx.jpeg",
  "niche": "fashion",
  "avgViews": 1006567,
  "engagementRate": 531.31,
  "bio": "Where's my Toji?😭\\n#ilovemyfollowers\\nLet's hit 50K?",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T23:08:25.082Z"
},
  {
  "handle": "alizechinchilla",
  "profileUrl": "https://www.tiktok.com/@alizechinchilla",
  "followers": 40800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/alizechinchilla.jpeg",
  "niche": "fashion",
  "avgViews": 517533,
  "engagementRate": 140.67,
  "bio": "41k?\\n💌Alizec.collab@gmail.com\\nIg:alizechinchilla\\nBackup Acc @𝐀𝐀",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T23:10:19.683Z"
},
  {
  "handle": "xmidnightfae",
  "profileUrl": "https://www.tiktok.com/@xmidnightfae",
  "followers": 73600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/xmidnightfae.jpeg",
  "niche": "fashion",
  "avgViews": 146309,
  "engagementRate": 29.94,
  "bio": "⋆୨୧˚ ⋆ 🗝️ ⋆ ˚ ꩜\\n📩 bymidnightfae@gmail.com\\n♥︎ shop my fits ↓\\ndepop: midnightfae",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T23:13:19.949Z"
},
  {
  "handle": "anahi.miranda23",
  "profileUrl": "https://www.tiktok.com/@anahi.miranda23",
  "followers": 42300,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/anahi.miranda23.jpeg",
  "niche": "fashion",
  "avgViews": 1164993,
  "engagementRate": 102.73,
  "bio": "Fb 📲 https:\\u002F\\u002Fm.facebook.com\\u002Felleganceclothes-103459301523697\\u002F?ref=bookmarks",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T23:15:45.330Z"
},
  {
  "handle": "santiagohnndz_",
  "profileUrl": "https://www.tiktok.com/@santiagohnndz_",
  "followers": 51100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/santiagohnndz_.jpeg",
  "niche": "fashion",
  "avgViews": 2049930,
  "engagementRate": 71.22,
  "bio": "Outfit ideas • Fashion\\n20% OFF @Chevignon CÓDIGO: SANTIAGOHNN\\n@The Subject",
  "country": "spa",
  "lastScrapedAt": "2025-09-14T23:16:53.242Z"
},
  {
  "handle": "nesaglee",
  "profileUrl": "https://www.tiktok.com/@nesaglee",
  "followers": 26000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/nesaglee.jpeg",
  "niche": "fashion",
  "avgViews": 672474,
  "engagementRate": 140.06,
  "bio": "Alicja\\n🤍✨👟✈️\\nLondon\\n💌nesaglee@icloud.com💌\\nshop my outfits on LTK⬇️",
  "country": "eng",
  "lastScrapedAt": "2025-09-14T23:18:12.396Z"
},
];

async function main() {
  for (const tiktoker of tiktokers) {
    await prisma.tiktoker.upsert({
      where: { handle: tiktoker.handle },
      update: tiktoker,
      create: tiktoker,
    });
  }
}

main()
  .then(() => {
    console.log("✅ Seed completado");
    return prisma.$disconnect();
  })
  .catch((e) => {
    console.error("❌ Error al hacer seed:", e);
    return prisma.$disconnect();
  });