/// <reference types="node" />

import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

  const tiktokers = [
    {
  "handle": "madelyn_watkins",
  "profileUrl": "https://www.tiktok.com/@madelyn_watkins",
  "followers": 40300,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/madelyn_watkins.jpeg",
  "niche": "vlog",
  "avgViews": 53057,
  "engagementRate": 27.6,
  "bio": "😇🎧🦋✨🩵\\nATL | 25\\n💌: madelynwatkins09@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T06:02:55.410Z"
},
  {
  "handle": "iluosay",
  "profileUrl": "https://www.tiktok.com/@iluosay",
  "followers": 40500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/iluosay.jpeg",
  "niche": "vlog",
  "avgViews": 24955,
  "engagementRate": 9.13,
  "bio": "🧚🏻‍♂️just my dairy🧚🏻‍♂️\\n\\nlong videos on youtube: luosay",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T06:03:58.681Z"
},
  {
  "handle": "briee428",
  "profileUrl": "https://www.tiktok.com/@briee428",
  "followers": 37100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/briee428.jpeg",
  "niche": "vlog",
  "avgViews": 391210,
  "engagementRate": 28.02,
  "bio": "📒  ིྀ !  Briee's Diary ⋆ ˚. 🍰 ｡⋆౨ৎ˚\\n \\n₊ ⊹🍪 ✧˚   A Day in My Life  ⋆˚🥛˖°",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T06:05:55.661Z"
},
  {
  "handle": "vlogswtosia",
  "profileUrl": "https://www.tiktok.com/@vlogswtosia",
  "followers": 54900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/vlogswtosia.jpeg",
  "niche": "vlog",
  "avgViews": 4957,
  "engagementRate": 1.73,
  "bio": "💌: vlogswtosia@gmail.com\\nLifestyle, beauty, fashion \\nWarsaw,Poland\\n✨🌸🧖🏼‍♀️🎀",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T06:06:24.041Z"
},
  {
  "handle": "thitaandbudba",
  "profileUrl": "https://www.tiktok.com/@thitaandbudba",
  "followers": 41200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/thitaandbudba.jpeg",
  "niche": "vlog",
  "avgViews": 629331,
  "engagementRate": 166.11,
  "bio": "IG :s_somsem\\n\\nfor work \\nline:0615426492",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T06:07:15.303Z"
},
  {
  "handle": "joelinejst",
  "profileUrl": "https://www.tiktok.com/@joelinejst",
  "followers": 10500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/joelinejst.jpeg",
  "niche": "vlog",
  "avgViews": 35780,
  "engagementRate": 108.26,
  "bio": "lifestyle, motivation, selfcare and more\\nig: joelinejst\\n💌 joeline.jst@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T06:08:03.288Z"
},
  {
  "handle": "skinfix",
  "profileUrl": "https://www.tiktok.com/@skinfix",
  "followers": 55000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/skinfix.jpeg",
  "niche": "vlog",
  "avgViews": 549,
  "engagementRate": 0.07,
  "bio": "Clean, clinical, high-impact skincare\\n🛒 Sephora 🇺🇸🇨🇦🇬🇧🇦🇺 Amazon Kohl's",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T06:09:49.611Z"
},
  {
  "handle": "butenk_nataliia",
  "profileUrl": "https://www.tiktok.com/@butenk_nataliia",
  "followers": 43400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/butenk_nataliia.jpeg",
  "niche": "vlog",
  "avgViews": 1231550,
  "engagementRate": 37.91,
  "bio": "🎀 My morning routine is a habit I love to share🎀\\n💌 Butenknataliia25@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T06:10:32.019Z"
},
  {
  "handle": "batuev_contortion",
  "profileUrl": "https://www.tiktok.com/@batuev_contortion",
  "followers": 25000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/batuev_contortion.jpeg",
  "niche": "vlog",
  "avgViews": 357106,
  "engagementRate": 26.62,
  "bio": "Info about classes you will find in my instagram ( or write me direct there)",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T06:11:35.081Z"
},
  {
  "handle": "dreamdiorsworld",
  "profileUrl": "https://www.tiktok.com/@dreamdiorsworld",
  "followers": 14400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/dreamdiorsworld.jpeg",
  "niche": "vlog",
  "avgViews": 1302,
  "engagementRate": 0.62,
  "bio": "Official Account Of Dream Dior's World🎀\\nYouTuber🎀\\nSubscribeeeeeee⬇️",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T06:12:56.020Z"
},
  {
  "handle": "trici_ann",
  "profileUrl": "https://www.tiktok.com/@trici_ann",
  "followers": 24500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/trici_ann.jpeg",
  "niche": "vlog",
  "avgViews": 166312,
  "engagementRate": 66.72,
  "bio": "Email: gtriciann@gmail.com\\nHair | Lifestyle | Vlogs 💅🏽",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T06:13:39.501Z"
},
  {
  "handle": "byy.nour3",
  "profileUrl": "https://www.tiktok.com/@byy.nour3",
  "followers": 25000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/byy.nour3.jpeg",
  "niche": "vlog",
  "avgViews": 15366,
  "engagementRate": 10.44,
  "bio": "Sharing modest fashion & beauty finds | Lifestyle & tips🧴🍵🧸",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T06:14:46.647Z"
},
  {
  "handle": "aprilplss",
  "profileUrl": "https://www.tiktok.com/@aprilplss",
  "followers": 18200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/aprilplss.jpeg",
  "niche": "vlog",
  "avgViews": 368576,
  "engagementRate": 457.19,
  "bio": "fashion & makeup\\n💌 abrildaniela.martinezg@gmail.com\\nig: aprilplss\\n🦢",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T06:16:19.092Z"
},
  {
  "handle": "fergonzalezzzn",
  "profileUrl": "https://www.tiktok.com/@fergonzalezzzn",
  "followers": 38700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/fergonzalezzzn.jpeg",
  "niche": "vlog",
  "avgViews": 4281,
  "engagementRate": 0.57,
  "bio": "lifestyle | mindset | beauty \\n\\n👇🏼te enseño a editar y crear videos desde 0",
  "country": "spa",
  "lastScrapedAt": "2025-09-17T06:16:47.710Z"
},
  {
  "handle": "lexrayn",
  "profileUrl": "https://www.tiktok.com/@lexrayn",
  "followers": 43000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/lexrayn.jpeg",
  "niche": "vlog",
  "avgViews": 268918,
  "engagementRate": 129.75,
  "bio": "Welcome to my digital diary 💭\\ndecor • fashion • lifestyle\\n📧: Lexrayn@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T06:17:21.131Z"
},
  {
  "handle": "verci.cx",
  "profileUrl": "https://www.tiktok.com/@verci.cx",
  "followers": 13100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/verci.cx.jpeg",
  "niche": "vlog",
  "avgViews": 1125,
  "engagementRate": 1.15,
  "bio": "☁️🥥🤍🪽\\n⇣ pr\\u002Fcollab ⇣\\n✉️: juliaverci@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T06:18:04.467Z"
},
{
  "handle": "emmmck",
  "profileUrl": "https://www.tiktok.com/@emmmck",
  "followers": 54500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/emmmck.jpeg",
  "niche": "vlog",
  "avgViews": 31879,
  "engagementRate": 3.65,
  "bio": "vancouver\\nwellness, lifestyle + content tips \\n💌 info.emmmck@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:25:26.398Z"
},
  {
  "handle": "everydaypauli",
  "profileUrl": "https://www.tiktok.com/@everydaypauli",
  "followers": 19900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/everydaypauli.jpeg",
  "niche": "vlog",
  "avgViews": 32089,
  "engagementRate": 7.51,
  "bio": "my life and lifts\\n💌 everydaypauli@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:25:54.964Z"
},
  {
  "handle": "_barbaramillaray",
  "profileUrl": "https://www.tiktok.com/@_barbaramillaray",
  "followers": 74300,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/_barbaramillaray.jpeg",
  "niche": "vlog",
  "avgViews": 252108,
  "engagementRate": 39.55,
  "bio": "holi holi 😙🌸\\nIG \\",
  "country": "spa",
  "lastScrapedAt": "2025-09-17T17:26:23.491Z"
},
  {
  "handle": "brunellachevalier",
  "profileUrl": "https://www.tiktok.com/@brunellachevalier",
  "followers": 18700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/brunellachevalier.jpeg",
  "niche": "vlog",
  "avgViews": 243777,
  "engagementRate": 45.27,
  "bio": "vlogs & actividades • hauls • moda\\n💌 brunechevalier@gmail.com",
  "country": "spa",
  "lastScrapedAt": "2025-09-17T17:27:04.872Z"
},
  {
  "handle": "thewetbrush",
  "profileUrl": "https://www.tiktok.com/@thewetbrush",
  "followers": 70700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/thewetbrush.jpeg",
  "niche": "vlog",
  "avgViews": 6859,
  "engagementRate": 0.24,
  "bio": "Official TikTok Of The Original Detangler \\n🏆 Award-Winning 💁‍♀️ All Hair Types",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:27:38.493Z"
},
  {
  "handle": "chzukekii",
  "profileUrl": "https://www.tiktok.com/@chzukekii",
  "followers": 22400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/chzukekii.jpeg",
  "niche": "vlog",
  "avgViews": 86225,
  "engagementRate": 46.32,
  "bio": "jakarta | chzukekii@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:29:05.255Z"
},
  {
  "handle": "starlitdels",
  "profileUrl": "https://www.tiktok.com/@starlitdels",
  "followers": 34000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/starlitdels.jpeg",
  "niche": "vlog",
  "avgViews": 3431,
  "engagementRate": 2.19,
  "bio": "🧸 safe place for you ♡\\ninsta: bydelsss_\\nyoutube: bydels ↓\\nblehsynadel@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:29:39.253Z"
},
  {
  "handle": "caminievar",
  "profileUrl": "https://www.tiktok.com/@caminievar",
  "followers": 19500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/caminievar.jpeg",
  "niche": "vlog",
  "avgViews": 131067,
  "engagementRate": 60.31,
  "bio": "mi diario visual ☁️\\n💌 camilanievaph@gmail.com",
  "country": "spa",
  "lastScrapedAt": "2025-09-17T17:30:08.024Z"
},
  {
  "handle": "ieuniversity",
  "profileUrl": "https://www.tiktok.com/@ieuniversity",
  "followers": 38500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/ieuniversity.jpeg",
  "niche": "vlog",
  "avgViews": 86955,
  "engagementRate": 7.97,
  "bio": "Don’t mind me, just driving innovation 🚀\\nIE University 🌍\\n#GoingtoIE",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:30:50.476Z"
},
  {
  "handle": "siriural",
  "profileUrl": "https://www.tiktok.com/@siriural",
  "followers": 39200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/siriural.jpeg",
  "niche": "vlog",
  "avgViews": 9253,
  "engagementRate": 3.38,
  "bio": "busy romanticizing\\n\\nsiri.ural@outlook.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:31:33.710Z"
},
  {
  "handle": "caamirodriguez",
  "profileUrl": "https://www.tiktok.com/@caamirodriguez",
  "followers": 27500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/caamirodriguez.jpeg",
  "niche": "vlog",
  "avgViews": 48018,
  "engagementRate": 30.66,
  "bio": "Vlogs, life y girl energy ✨\\nIg @caamiii_rodriguez\\ncaaaaammiiii@gmail.com 💌",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:32:21.443Z"
},
  {
  "handle": "lucastorgesenn",
  "profileUrl": "https://www.tiktok.com/@lucastorgesenn",
  "followers": 39600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/lucastorgesenn.jpeg",
  "niche": "vlog",
  "avgViews": 148555,
  "engagementRate": 73.76,
  "bio": "YouTube: Lucas Torgesen\\nInsta: lucastorgesenn\\nlucastorgesen@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:32:50.381Z"
},
  {
  "handle": "trici_ann",
  "profileUrl": "https://www.tiktok.com/@trici_ann",
  "followers": 24500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/trici_ann.jpeg",
  "niche": "vlog",
  "avgViews": 166793,
  "engagementRate": 66.88,
  "bio": "Email: gtriciann@gmail.com\\nHair | Lifestyle | Vlogs 💅🏽",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:33:41.835Z"
},
  {
  "handle": "tatianamek",
  "profileUrl": "https://www.tiktok.com/@tatianamek",
  "followers": 51400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/tatianamek.jpeg",
  "niche": "vlog",
  "avgViews": 1494,
  "engagementRate": 0.32,
  "bio": "los angeles 🪽\\n💌 tatiana@pctalent.co",
  "country": "spa",
  "lastScrapedAt": "2025-09-17T17:34:24.886Z"
},
  {
  "handle": "tyler.elaine",
  "profileUrl": "https://www.tiktok.com/@tyler.elaine",
  "followers": 16500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/tyler.elaine.jpeg",
  "niche": "vlog",
  "avgViews": 8667,
  "engagementRate": 14.13,
  "bio": "🎀🕯️☁️ 🧴 \\nIG: tylerelainee\\n💌: Elaineporter2001@gmail.com",
  "country": "nob",
  "lastScrapedAt": "2025-09-17T17:36:13.762Z"
},
  {
  "handle": "makaylasieb",
  "profileUrl": "https://www.tiktok.com/@makaylasieb",
  "followers": 10700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/makaylasieb.jpeg",
  "niche": "vlog",
  "avgViews": 82269,
  "engagementRate": 106.46,
  "bio": "nursing journey\\n🧠🫶🏼🩺",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:36:48.043Z"
},
  {
  "handle": "sofiakonincks",
  "profileUrl": "https://www.tiktok.com/@sofiakonincks",
  "followers": 45000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/sofiakonincks.jpeg",
  "niche": "vlog",
  "avgViews": 19391,
  "engagementRate": 7.75,
  "bio": "Wellness, routines & fits ✩⡡\\n✉️: sofiakonincks@outlook.com\\nDutch | 21",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:37:55.524Z"
},
  {
  "handle": "jaswinterr",
  "profileUrl": "https://www.tiktok.com/@jaswinterr",
  "followers": 52600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/jaswinterr.jpeg",
  "niche": "vlog",
  "avgViews": 42846,
  "engagementRate": 18.78,
  "bio": "20 | UK\\njasmine@beaumondeagency.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:38:29.036Z"
},
  {
  "handle": "annika.stevie",
  "profileUrl": "https://www.tiktok.com/@annika.stevie",
  "followers": 20900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/annika.stevie.jpeg",
  "niche": "vlog",
  "avgViews": 76302,
  "engagementRate": 26.52,
  "bio": "internet bestie 🪽 Texas\\n💌 annika.stevie@dulcedo.com\\nyt channel ⤵️",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:38:57.094Z"
},
  {
  "handle": "asha.diaries",
  "profileUrl": "https://www.tiktok.com/@asha.diaries",
  "followers": 29100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/asha.diaries.jpeg",
  "niche": "vlog",
  "avgViews": 27460,
  "engagementRate": 16.7,
  "bio": "join my quiet world🪐\\nSelf care & things I love \\n📩ashadiaries08@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:39:31.363Z"
},
  {
  "handle": "cassidyvoase",
  "profileUrl": "https://www.tiktok.com/@cassidyvoase",
  "followers": 57200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/cassidyvoase.jpeg",
  "niche": "vlog",
  "avgViews": 53721,
  "engagementRate": 19.61,
  "bio": "ohio !!!\\n🧁💌🏡🧺🍓\\nemily.angelo@grail-talent.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:40:01.301Z"
},
  {
  "handle": "mxvnns",
  "profileUrl": "https://www.tiktok.com/@mxvnns",
  "followers": 23600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/mxvnns.jpeg",
  "niche": "vlog",
  "avgViews": 274080,
  "engagementRate": 78.44,
  "bio": "15 | self improvement\\n┈┈┈┈┈┈┈┈┈┈┈┈\\nTry Brain.FM free for 30 days 🎧 ↙️",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:40:45.762Z"
},
  {
  "handle": "sifsdiary",
  "profileUrl": "https://www.tiktok.com/@sifsdiary",
  "followers": 73800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/sifsdiary.jpeg",
  "niche": "vlog",
  "avgViews": 13776,
  "engagementRate": 5.23,
  "bio": "Boston, MA\\n🎀🪩💫 ✧･ﾟ\\n@sif.pagh.christensen@icloud.com\\nYesStyle code: SIFDIA08",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:41:13.475Z"
},
  {
  "handle": "romy.spk",
  "profileUrl": "https://www.tiktok.com/@romy.spk",
  "followers": 59200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/romy.spk.jpeg",
  "niche": "vlog",
  "avgViews": 4592,
  "engagementRate": 1.42,
  "bio": "uni, selfcare & romantizing life \\n💌romy@spek.me",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:41:42.511Z"
},
  {
  "handle": "r.okive",
  "profileUrl": "https://www.tiktok.com/@r.okive",
  "followers": 54000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/r.okive.jpeg",
  "niche": "vlog",
  "avgViews": 9692,
  "engagementRate": 3.74,
  "bio": "ro’s archive \\ndigital diary\\n💌: roskive@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:42:11.167Z"
},
  {
  "handle": "iiamsalvedoll_26",
  "profileUrl": "https://www.tiktok.com/@iiamsalvedoll_26",
  "followers": 16900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/iiamsalvedoll_26.jpeg",
  "niche": "vlog",
  "avgViews": 638845,
  "engagementRate": 215.24,
  "bio": "",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:42:43.602Z"
},
  {
  "handle": "_maitoyo",
  "profileUrl": "https://www.tiktok.com/@_maitoyo",
  "followers": 45800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/_maitoyo.jpeg",
  "niche": "vlog",
  "avgViews": 46372,
  "engagementRate": 25.58,
  "bio": "lifestyle | beauty | wellness\\n📍 toronto \\n💌 maitoyo02@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:43:45.509Z"
},
  {
  "handle": "ferlegar",
  "profileUrl": "https://www.tiktok.com/@ferlegar",
  "followers": 15500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/ferlegar.jpeg",
  "niche": "vlog",
  "avgViews": 1570,
  "engagementRate": 0.83,
  "bio": "ig: @ferlegarreta \\nsan diego \\n💌flegarretar@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:44:27.754Z"
},
  {
  "handle": "__jackiemo",
  "profileUrl": "https://www.tiktok.com/@__jackiemo",
  "followers": 17000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/__jackiemo.jpeg",
  "niche": "vlog",
  "avgViews": 16345,
  "engagementRate": 6.54,
  "bio": "J E S U S 🤍 \\nA little haul of my life 🫶🏼\\njackiemoralescox@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:44:57.724Z"
},
  {
  "handle": "jeessva",
  "profileUrl": "https://www.tiktok.com/@jeessva",
  "followers": 12000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/jeessva.jpeg",
  "niche": "vlog",
  "avgViews": 31586,
  "engagementRate": 48.8,
  "bio": "stockholm 🪐\\nugc\\u002Fcollab: 📧 jeessva@outlook.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:45:27.992Z"
},
  {
  "handle": "nikkkki.08",
  "profileUrl": "https://www.tiktok.com/@nikkkki.08",
  "followers": 13700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/nikkkki.08.jpeg",
  "niche": "vlog",
  "avgViews": 96555,
  "engagementRate": 140.64,
  "bio": "dallas\\ndigital diary \\u003C3 | 21\\nig: nikkimaria.xo\\n💌 nikkimd.v8@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:46:54.243Z"
},
  {
  "handle": "naomichaaannn",
  "profileUrl": "https://www.tiktok.com/@naomichaaannn",
  "followers": 58500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/naomichaaannn.jpeg",
  "niche": "vlog",
  "avgViews": 6354,
  "engagementRate": 4.04,
  "bio": "digital diary ᶻ 𝗓 𐰁 .ᐟ\\ni love skincare & matcha\\n✉️ : naomichaaannn@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:47:28.523Z"
},
  {
  "handle": "kxrpova0",
  "profileUrl": "https://www.tiktok.com/@kxrpova0",
  "followers": 50700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/kxrpova0.jpeg",
  "niche": "vlog",
  "avgViews": 469250,
  "engagementRate": 98.44,
  "bio": "Ksenia 🤎\\n20 yo\\nWelcome :)",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:48:01.865Z"
},
  {
  "handle": "roosilline",
  "profileUrl": "https://www.tiktok.com/@roosilline",
  "followers": 10400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/roosilline.jpeg",
  "niche": "vlog",
  "avgViews": 4227,
  "engagementRate": 4.76,
  "bio": "🍵 ⭐️ 🧿\\ncollab.gulseli@gmail.com 💌",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:48:31.507Z"
},
  {
  "handle": "gina_najjar",
  "profileUrl": "https://www.tiktok.com/@gina_najjar",
  "followers": 27400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/gina_najjar.jpeg",
  "niche": "vlog",
  "avgViews": 158082,
  "engagementRate": 46.43,
  "bio": "co-founder @allcreators__ \\nalso corporate girl \\ndubai | spain",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:49:23.651Z"
},
  {
  "handle": "shaaayyaaaa",
  "profileUrl": "https://www.tiktok.com/@shaaayyaaaa",
  "followers": 38700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/shaaayyaaaa.jpeg",
  "niche": "vlog",
  "avgViews": 2409,
  "engagementRate": 1.15,
  "bio": "💌 helloshayaa@gmail.com\\na little bit of everything \\n📍germany\\n   🧁",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:49:56.618Z"
},
  {
  "handle": "mepluss",
  "profileUrl": "https://www.tiktok.com/@mepluss",
  "followers": 62700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/mepluss.jpeg",
  "niche": "vlog",
  "avgViews": 77950,
  "engagementRate": 4.74,
  "bio": "Daily routine planner\\nBe your better self with Me+ app\\nEmail:katrin@enerjoy.life",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:50:52.718Z"
},
  {
  "handle": "stacylimm",
  "profileUrl": "https://www.tiktok.com/@stacylimm",
  "followers": 56000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/stacylimm.jpeg",
  "niche": "vlog",
  "avgViews": 646069,
  "engagementRate": 259.38,
  "bio": "just a human of cinema \\nin big messy world",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:51:27.703Z"
},
  {
  "handle": "baartzzzz",
  "profileUrl": "https://www.tiktok.com/@baartzzzz",
  "followers": 60700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/baartzzzz.jpeg",
  "niche": "vlog",
  "avgViews": 293468,
  "engagementRate": 10.17,
  "bio": "˚˖𓍢ִ໋🦢˚\\n\\n✿ room • daily life ✿\\ncollab dm ig : baartzzzzz\\nlink yt 👇🏻",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:52:04.817Z"
},
  {
  "handle": "philip.udogu",
  "profileUrl": "https://www.tiktok.com/@philip.udogu",
  "followers": 39300,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/philip.udogu.jpeg",
  "niche": "vlog",
  "avgViews": 81350,
  "engagementRate": 19.63,
  "bio": "DAY IN THE LIFE\\nOF A BALLER\\nphilip.info@gmx.de",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:52:37.086Z"
},
  {
  "handle": "strawbeiui",
  "profileUrl": "https://www.tiktok.com/@strawbeiui",
  "followers": 23500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/strawbeiui.jpeg",
  "niche": "vlog",
  "avgViews": 2382,
  "engagementRate": 1.59,
  "bio": "documenting life | 🎬🧺🌷🪞\\ninstagram: @strawbeiui\\n📧 strawbeiui@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:53:20.920Z"
},
  {
  "handle": "willowpickle444",
  "profileUrl": "https://www.tiktok.com/@willowpickle444",
  "followers": 63100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/willowpickle444.jpeg",
  "niche": "vlog",
  "avgViews": 72963,
  "engagementRate": 25.66,
  "bio": "˖◛⁺⑅ willowmorris444@gmail.com\\n\\n🎐IG sitaravogue",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:54:09.430Z"
},
  {
  "handle": "kth_vll",
  "profileUrl": "https://www.tiktok.com/@kth_vll",
  "followers": 12200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/kth_vll.jpeg",
  "niche": "vlog",
  "avgViews": 600678,
  "engagementRate": 903.31,
  "bio": "﹒⪩⪨﹒\\n20een જ esfp-t\\n💌 : jklsv.business@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:54:37.548Z"
},
  {
  "handle": "iluosay",
  "profileUrl": "https://www.tiktok.com/@iluosay",
  "followers": 40900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/iluosay.jpeg",
  "niche": "vlog",
  "avgViews": 32794,
  "engagementRate": 11.39,
  "bio": "🧚🏻‍♂️just my dairy🧚🏻‍♂️\\n\\nlong videos on youtube: luosay",
  "country": "eng",
  "lastScrapedAt": "2025-09-17T17:55:16.552Z"
},
{
  "handle": "tyson.v_",
  "profileUrl": "https://www.tiktok.com/@tyson.v_",
  "followers": 16700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/tyson.v_.jpeg",
  "niche": "marketing",
  "avgViews": 714,
  "engagementRate": 0.28,
  "bio": "🌴 Nomad: Travel, Lift, Learn \\n🧠 Seek truth, master freedom\\n👇🏽 Join me",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T07:52:47.821Z"
},
  {
  "handle": "officialtimhess",
  "profileUrl": "https://www.tiktok.com/@officialtimhess",
  "followers": 21600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/officialtimhess.jpeg",
  "niche": "marketing",
  "avgViews": 762,
  "engagementRate": 0.23,
  "bio": "No whatsapp\\u002Ftelagram \\nShare how to make income online\\nI go live 8am And 5pm PST",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T07:53:27.726Z"
},
  {
  "handle": "coachtotty",
  "profileUrl": "https://www.tiktok.com/@coachtotty",
  "followers": 74400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/coachtotty.jpeg",
  "niche": "marketing",
  "avgViews": 8876,
  "engagementRate": 0.25,
  "bio": "Your TikTok Shop Mentor📝\\nBecome A Tiktok Shop Affiliate⬇️\\nMy ONLY page🚨",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T07:53:56.744Z"
},
  {
  "handle": "ddigitalstudio_",
  "profileUrl": "https://www.tiktok.com/@ddigitalstudio_",
  "followers": 17100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/ddigitalstudio_.jpeg",
  "niche": "marketing",
  "avgViews": 124845,
  "engagementRate": 13.81,
  "bio": "Sharing all my digital marketing tips✨🤍\\nOFFICIAL ACCOUNT\\nFree guide linked ⬇️",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T07:54:36.808Z"
},
  {
  "handle": "face.it.girl",
  "profileUrl": "https://www.tiktok.com/@face.it.girl",
  "followers": 13200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/face.it.girl.jpeg",
  "niche": "marketing",
  "avgViews": 21725,
  "engagementRate": 4.55,
  "bio": "💸Teaching girls how to make money online\\n\\n🚫I Don't DM\\n\\n 🎥Live daily @12:00",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T07:55:15.166Z"
},
  {
  "handle": "digitalbabe.sav",
  "profileUrl": "https://www.tiktok.com/@digitalbabe.sav",
  "followers": 15400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/digitalbabe.sav.jpeg",
  "niche": "marketing",
  "avgViews": 3505,
  "engagementRate": 0.77,
  "bio": "MY ONLY PAGE!!!\\nIG- Digitalbabe.Sav\\nGet started w\\u002F your digital products below⬇️",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T07:55:48.545Z"
},
  {
  "handle": "khaleiwaldrop",
  "profileUrl": "https://www.tiktok.com/@khaleiwaldrop",
  "followers": 64500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/khaleiwaldrop.jpeg",
  "niche": "marketing",
  "avgViews": 184389,
  "engagementRate": 53.15,
  "bio": "MORNING VLOGS, MOM LIFE + MORE\\n💌 manager: danielle@ferraramedia.com\\nLinks👇🏼",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T07:56:22.018Z"
},
  {
  "handle": "thepassiveincomegurl",
  "profileUrl": "https://www.tiktok.com/@thepassiveincomegurl",
  "followers": 12200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/thepassiveincomegurl.jpeg",
  "niche": "marketing",
  "avgViews": 925,
  "engagementRate": 0.22,
  "bio": "Make 💰 from your 📲 \\n💸 $1M+ in sales\\n💌 Msg me on lG 👉🏻 @passiveincomegurl\\nFREE TRAINING 👩🏼‍💻👇🏻",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T07:57:11.168Z"
},
  {
  "handle": "moonlightfemme",
  "profileUrl": "https://www.tiktok.com/@moonlightfemme",
  "followers": 68000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/moonlightfemme.jpeg",
  "niche": "marketing",
  "avgViews": 48588,
  "engagementRate": 21.27,
  "bio": "All things digital marketing, passive income & \\nmindset🖤 \\ncreate your dream life selling Digital Products↓",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T07:57:38.627Z"
},
  {
  "handle": "beacons.ai",
  "profileUrl": "https://www.tiktok.com/@beacons.ai",
  "followers": 15800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/beacons.ai.jpeg",
  "niche": "marketing",
  "avgViews": 184969,
  "engagementRate": 2,
  "bio": "Tools to earn 🛠️ Data to grow 📈 A platform built for creators & brands 🤝",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T07:58:19.792Z"
},
  {
  "handle": "effortless.digita",
  "profileUrl": "https://www.tiktok.com/@effortless.digita",
  "followers": 18300,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/effortless.digita.jpeg",
  "niche": "marketing",
  "avgViews": 554,
  "engagementRate": 0.15,
  "bio": "Turn 📲 into a 🏧 with digital products💸",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T07:58:49.279Z"
},
  {
  "handle": "dianaa.marketing",
  "profileUrl": "https://www.tiktok.com/@dianaa.marketing",
  "followers": 23000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/dianaa.marketing.jpeg",
  "niche": "marketing",
  "avgViews": 20139,
  "engagementRate": 16.99,
  "bio": "Make WiFi money w\\u002F me 💸📲\\nIG: dianaa.marketing",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T07:59:28.876Z"
},
  {
  "handle": "bizwithmichael",
  "profileUrl": "https://www.tiktok.com/@bizwithmichael",
  "followers": 42900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/bizwithmichael.jpeg",
  "niche": "marketing",
  "avgViews": 126225,
  "engagementRate": 13.57,
  "bio": "🤘Helping ordinary people earn with social media\\nLive Webinar\\u002Fget started👇",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T07:59:59.581Z"
},
  {
  "handle": "exito.03",
  "profileUrl": "https://www.tiktok.com/@exito.03",
  "followers": 15500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/exito.03.jpeg",
  "niche": "marketing",
  "avgViews": 251459,
  "engagementRate": 149.7,
  "bio": "Mentalidad Ganadora⭐|✅ \\n| Marketing,trading,dropshiping l 👤✅|\\n👇Unete Al  1%👇",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:01:52.428Z"
},
  {
  "handle": "jainmymartinez",
  "profileUrl": "https://www.tiktok.com/@jainmymartinez",
  "followers": 19400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/jainmymartinez.jpeg",
  "niche": "marketing",
  "avgViews": 9669,
  "engagementRate": 4.82,
  "bio": "De $0 a 6.1M vendidos online, ayudo a cualquiera a generar💸WEBINAR GRATIS HOY👇",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:03:31.676Z"
},
  {
  "handle": "jes.gestiondigital",
  "profileUrl": "https://www.tiktok.com/@jes.gestiondigital",
  "followers": 31100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/jes.gestiondigital.jpeg",
  "niche": "marketing",
  "avgViews": 939,
  "engagementRate": 0.09,
  "bio": "Redes Sociales👩🏼‍💻 Un poco de mi🦋 Guardá los tips💓 propuestas x IG👇🏼",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:04:10.642Z"
},
  {
  "handle": "natiyehaikel",
  "profileUrl": "https://www.tiktok.com/@natiyehaikel",
  "followers": 19300,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/natiyehaikel.jpeg",
  "niche": "marketing",
  "avgViews": 39596,
  "engagementRate": 14.05,
  "bio": "Cristiana, esposa y psicopedagoga viviendo 100% de internet ⚡️ ÚNICA CUENTA✅",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:04:44.968Z"
},
  {
  "handle": "susanadeniz02",
  "profileUrl": "https://www.tiktok.com/@susanadeniz02",
  "followers": 26600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/susanadeniz02.jpeg",
  "niche": "marketing",
  "avgViews": 1196,
  "engagementRate": 0.38,
  "bio": "IG: @susanaguerra.ugc\\nMonetiza con tus redes sociales \\n⬇️ TE EXPLICO AQUÍ⬇️",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:05:43.409Z"
},
  {
  "handle": "ramirogabrielgc",
  "profileUrl": "https://www.tiktok.com/@ramirogabrielgc",
  "followers": 34300,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/ramirogabrielgc.jpeg",
  "niche": "marketing",
  "avgViews": 37557,
  "engagementRate": 3.65,
  "bio": "Aprende Marketing digital que SI funciona. Entra a mi comunidad Gratis 👇",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:06:57.658Z"
},
  {
  "handle": "ivannavalentinaa",
  "profileUrl": "https://www.tiktok.com/@ivannavalentinaa",
  "followers": 41200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/ivannavalentinaa.jpeg",
  "niche": "marketing",
  "avgViews": 94358,
  "engagementRate": 17.58,
  "bio": "Ig: @ivannavalentinar\\nEstratega digital\\n👇🏻Mira la CLASE GRATIS👇🏻",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:07:42.100Z"
},
  {
  "handle": "seaguilar",
  "profileUrl": "https://www.tiktok.com/@seaguilar",
  "followers": 43500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/seaguilar.jpeg",
  "niche": "marketing",
  "avgViews": 28290,
  "engagementRate": 2.95,
  "bio": "Aprende sobre negocios con explicaciones claras y paso por paso",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:08:16.271Z"
},
  {
  "handle": "the.socialgeek",
  "profileUrl": "https://www.tiktok.com/@the.socialgeek",
  "followers": 19000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/the.socialgeek.jpeg",
  "niche": "marketing",
  "avgViews": 3606,
  "engagementRate": 1.78,
  "bio": "SMM |UGC|PaidAds\\nLearn how to make $$ online faceless\\n📩Ukachukwutesia@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:09:33.310Z"
},
  {
  "handle": "kiaya.kilpack",
  "profileUrl": "https://www.tiktok.com/@kiaya.kilpack",
  "followers": 51000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/kiaya.kilpack.jpeg",
  "niche": "marketing",
  "avgViews": 6047,
  "engagementRate": 0.84,
  "bio": "Digital & Affiliate Marketing ✨\\nFREE Guide ⬇️",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:10:02.684Z"
},
  {
  "handle": "itsjessedee",
  "profileUrl": "https://www.tiktok.com/@itsjessedee",
  "followers": 11400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/itsjessedee.jpeg",
  "niche": "marketing",
  "avgViews": 2197,
  "engagementRate": 0.8,
  "bio": "24 | on my way to rebuilding & becoming her",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:10:31.166Z"
},
  {
  "handle": "successwithalley",
  "profileUrl": "https://www.tiktok.com/@successwithalley",
  "followers": 41300,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/successwithalley.jpeg",
  "niche": "marketing",
  "avgViews": 4949,
  "engagementRate": 0.35,
  "bio": "✨ SAHM helping anyone make money online\\n👇🏼Grab the 🆓 video guide👇🏼",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:11:15.201Z"
},
  {
  "handle": "pamelarikairi",
  "profileUrl": "https://www.tiktok.com/@pamelarikairi",
  "followers": 46800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/pamelarikairi.jpeg",
  "niche": "marketing",
  "avgViews": 71173,
  "engagementRate": 1.78,
  "bio": "Amo ver la vida de colores 🛼🌷🐚🪷\\n✨YouTube \\u002F ig: Pamela Arikairi\\nlinks 🔗👇🏻",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:11:46.051Z"
},
  {
  "handle": "ebac_latam",
  "profileUrl": "https://www.tiktok.com/@ebac_latam",
  "followers": 40400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/ebac_latam.jpeg",
  "niche": "marketing",
  "avgViews": 458771,
  "engagementRate": 52.48,
  "bio": "Cursos online de Diseño, Marketing, Programación y Data, Gaming, Fashion y más",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:12:15.991Z"
},
  {
  "handle": "markdigital.conandre",
  "profileUrl": "https://www.tiktok.com/@markdigital.conandre",
  "followers": 75500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/markdigital.conandre.jpeg",
  "niche": "marketing",
  "avgViews": 2915,
  "engagementRate": 0.23,
  "bio": "Ig:markdigital.conandre\\n⛔NO respondo comentarios con fotos\\n⬇️TODA LA INF AQUI⬇️",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:12:55.921Z"
},
  {
  "handle": "gabsofficialss",
  "profileUrl": "https://www.tiktok.com/@gabsofficialss",
  "followers": 65500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/gabsofficialss.jpeg",
  "niche": "marketing",
  "avgViews": 7081,
  "engagementRate": 0.27,
  "bio": "Helping 9-5 make money with digital products 💰\\n$0 -$10k in 2 months 💸",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:13:25.164Z"
},
  {
  "handle": "desimonefacu",
  "profileUrl": "https://www.tiktok.com/@desimonefacu",
  "followers": 12700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/desimonefacu.jpeg",
  "niche": "marketing",
  "avgViews": 648,
  "engagementRate": 0.25,
  "bio": "Las ventas son la sangre del negocio.",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:14:55.224Z"
},
  {
  "handle": "militappia",
  "profileUrl": "https://www.tiktok.com/@militappia",
  "followers": 58200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/militappia.jpeg",
  "niche": "marketing",
  "avgViews": 3430,
  "engagementRate": 0.34,
  "bio": "💌 milagrotapia222@gmail.com\\n\\necommerce | networkmarketing",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:15:24.115Z"
},
  {
  "handle": "facudestefano",
  "profileUrl": "https://www.tiktok.com/@facudestefano",
  "followers": 32200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/facudestefano.jpeg",
  "niche": "marketing",
  "avgViews": 74169,
  "engagementRate": 9.69,
  "bio": "Marketing Digital basado en RESULTADOS para trabajar remoto 🇺🇸\\n\\n⬇️ Mirá acá ⬇️",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:15:57.965Z"
},
  {
  "handle": "breetheaffiliate",
  "profileUrl": "https://www.tiktok.com/@breetheaffiliate",
  "followers": 28900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/breetheaffiliate.jpeg",
  "niche": "marketing",
  "avgViews": 1589,
  "engagementRate": 0.16,
  "bio": "Helping beginners hit 6-figs online 💻✨ \\n$506 4 days after start\\nSTART HERE👇🏻",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:16:29.727Z"
},
  {
  "handle": "imsandralapenta",
  "profileUrl": "https://www.tiktok.com/@imsandralapenta",
  "followers": 17000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/imsandralapenta.jpeg",
  "niche": "marketing",
  "avgViews": 313,
  "engagementRate": 0.14,
  "bio": "🙋🏻‍♀️Genero ingresos extra usando tiktok 🇻🇪 💸💸 Ver mas 👇",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:17:14.799Z"
},
  {
  "handle": "mechimansilla",
  "profileUrl": "https://www.tiktok.com/@mechimansilla",
  "followers": 45400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/mechimansilla.jpeg",
  "niche": "marketing",
  "avgViews": 77327,
  "engagementRate": 14.66,
  "bio": "Copywriter, marketer y freelancer 👩‍💻\\nCuenta de MKT 👉 @Mechi Mansilla",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:17:55.098Z"
},
  {
  "handle": "madhva2.0",
  "profileUrl": "https://www.tiktok.com/@madhva2.0",
  "followers": 31500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/madhva2.0.jpeg",
  "niche": "marketing",
  "avgViews": 1506,
  "engagementRate": 0.11,
  "bio": "🇭🇹 CNA Consultant Marketing Digital et Afilié #DWA #UGC 💵📌 #CEO",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:19:37.202Z"
},
  {
  "handle": "tizilavroff2",
  "profileUrl": "https://www.tiktok.com/@tizilavroff2",
  "followers": 46500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/tizilavroff2.jpeg",
  "niche": "marketing",
  "avgViews": 2626,
  "engagementRate": 0.18,
  "bio": "Emprendedora👩🏼‍💻\\nMás info en mi ig: tizilavroff",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:20:08.769Z"
},
  {
  "handle": "luisfossatidrop",
  "profileUrl": "https://www.tiktok.com/@luisfossatidrop",
  "followers": 43200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/luisfossatidrop.jpeg",
  "niche": "marketing",
  "avgViews": 12121,
  "engagementRate": 0.41,
  "bio": "Te enseño a vender por internet sin experiencia en mi Instagram 🤝",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:20:44.629Z"
},
  {
  "handle": "sergiosaac.co",
  "profileUrl": "https://www.tiktok.com/@sergiosaac.co",
  "followers": 15900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/sergiosaac.co.jpeg",
  "niche": "marketing",
  "avgViews": 201650,
  "engagementRate": 115.97,
  "bio": "Te ayudo a aumentar tus seguidores, hacer buen contenido y vender más⚡️🏀👇🏽",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:21:49.178Z"
},
  {
  "handle": "isabellaaamendez",
  "profileUrl": "https://www.tiktok.com/@isabellaaamendez",
  "followers": 35400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/isabellaaamendez.jpeg",
  "niche": "marketing",
  "avgViews": 8979,
  "engagementRate": 1.38,
  "bio": "Te enseño a generar con tu📱\\nDe 0 a 200K en 6 meses\\nMI ÚNICA CUENTA\\nInicia acá ↓",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:22:43.389Z"
},
  {
  "handle": "profitswithbaberenea",
  "profileUrl": "https://www.tiktok.com/@profitswithbaberenea",
  "followers": 29500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/profitswithbaberenea.jpeg",
  "niche": "marketing",
  "avgViews": 59189,
  "engagementRate": 7.66,
  "bio": "I DON'T SELL WIGS‼️\\n\\nReseller's hair supplier exposed ↴",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:23:12.199Z"
},
  {
  "handle": "justisaulnier",
  "profileUrl": "https://www.tiktok.com/@justisaulnier",
  "followers": 13000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/justisaulnier.jpeg",
  "niche": "marketing",
  "avgViews": 11603,
  "engagementRate": 3.42,
  "bio": "𝘾𝙧𝙚𝙖𝙣𝙙𝙤 𝙢𝙚𝙟𝙤𝙧𝙚𝙨 𝙫𝙚𝙧𝙨𝙞𝙤𝙣𝙚𝙨\\nᴇꜱᴛᴜᴅɪᴀɴᴛᴇ|ɴᴇᴛᴡᴏʀᴋᴇʀ|ᴇᴄᴏᴍᴍᴇʀᴄᴇ",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:24:15.235Z"
},
  {
  "handle": "lunamhamed",
  "profileUrl": "https://www.tiktok.com/@lunamhamed",
  "followers": 20000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/lunamhamed.jpeg",
  "niche": "marketing",
  "avgViews": 103624,
  "engagementRate": 46.19,
  "bio": "Creando comunidad emprendedora🫀\\n~ Lifestyle ~\\nINFO \\u003E\\u003E Ig. @Lunamhamed\\n👇🏼 Video explicativo de lo que hago👇🏼",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:24:45.449Z"
},
  {
  "handle": "jesusorozcomo",
  "profileUrl": "https://www.tiktok.com/@jesusorozcomo",
  "followers": 57100,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/jesusorozcomo.jpeg",
  "niche": "marketing",
  "avgViews": 592,
  "engagementRate": 0.08,
  "bio": "Yo que tú miraría este link \\n👇👇👇",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:25:34.989Z"
},
  {
  "handle": "emprende_cecy",
  "profileUrl": "https://www.tiktok.com/@emprende_cecy",
  "followers": 41200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/emprende_cecy.jpeg",
  "niche": "marketing",
  "avgViews": 16010,
  "engagementRate": 1.04,
  "bio": "Información \\nAqui \\n👇👇\\nsolo atiendo por WhatsApp. unica cuenta.",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:26:18.752Z"
},
  {
  "handle": "facelessearnings",
  "profileUrl": "https://www.tiktok.com/@facelessearnings",
  "followers": 13900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/facelessearnings.jpeg",
  "niche": "marketing",
  "avgViews": 33483,
  "engagementRate": 6.22,
  "bio": "💕Helping you earn passive income, faceless\\nTurn content ➡️💰\\n👇Start FREE today",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:27:04.101Z"
},
  {
  "handle": "lenieilarana",
  "profileUrl": "https://www.tiktok.com/@lenieilarana",
  "followers": 68800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/lenieilarana.jpeg",
  "niche": "marketing",
  "avgViews": 5678,
  "engagementRate": 0.45,
  "bio": "✅️ | Experta ventas LOW TICKET\\n💻 l Unica cuenta @lenieilarana\\n⭐️ l Te ayudo👇🏼",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:27:34.032Z"
},
{
  "handle": "best_spots_in",
  "profileUrl": "https://www.tiktok.com/@best_spots_in",
  "followers": 23900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/best_spots_in.jpeg",
  "niche": "travel",
  "avgViews": 3291610,
  "engagementRate": 2922.22,
  "bio": "sharing the best spots in ... 🌎\\n ☀️🥥🌴🐚",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:31:46.127Z"
},
  {
  "handle": "_eat_sleep_travel_repeat",
  "profileUrl": "https://www.tiktok.com/@_eat_sleep_travel_repeat",
  "followers": 58300,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/_eat_sleep_travel_repeat.jpeg",
  "niche": "travel",
  "avgViews": 503282,
  "engagementRate": 194.1,
  "bio": "Travel ↠ Adventure ↠ Lifestyle ↠ Interiors\\nBased in Bath, UK 🛁",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:32:17.737Z"
},
  {
  "handle": "dailymotivation.dose",
  "profileUrl": "https://www.tiktok.com/@dailymotivation.dose",
  "followers": 39000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/dailymotivation.dose.jpeg",
  "niche": "travel",
  "avgViews": 793373,
  "engagementRate": 125.47,
  "bio": "Get your motivation to travel the world :)",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:32:51.493Z"
},
  {
  "handle": "craig.peaks",
  "profileUrl": "https://www.tiktok.com/@craig.peaks",
  "followers": 31000,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/craig.peaks.jpeg",
  "niche": "travel",
  "avgViews": 718770,
  "engagementRate": 373.91,
  "bio": "peaktour@outlook.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:33:26.527Z"
},
  {
  "handle": "travelthecountrys",
  "profileUrl": "https://www.tiktok.com/@travelthecountrys",
  "followers": 13500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/travelthecountrys.jpeg",
  "niche": "travel",
  "avgViews": 880878,
  "engagementRate": 1591.39,
  "bio": "follow for more travel related content",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:33:55.561Z"
},
  {
  "handle": "hannahgentz",
  "profileUrl": "https://www.tiktok.com/@hannahgentz",
  "followers": 32400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/hannahgentz.jpeg",
  "niche": "travel",
  "avgViews": 13170,
  "engagementRate": 2.01,
  "bio": "wife - mama - always on the go\\n🌞🦋✨📖🧚‍♀️\\ncollabs + shop ⬇️",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:34:41.206Z"
},
  {
  "handle": "vavamadi",
  "profileUrl": "https://www.tiktok.com/@vavamadi",
  "followers": 11600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/vavamadi.jpeg",
  "niche": "travel",
  "avgViews": 14723,
  "engagementRate": 6.91,
  "bio": "Things I do & Places I go\\nSoCal\\nvavamadi22@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:35:30.625Z"
},
  {
  "handle": "natmi.ph",
  "profileUrl": "https://www.tiktok.com/@natmi.ph",
  "followers": 14500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/natmi.ph.jpeg",
  "niche": "travel",
  "avgViews": 1017,
  "engagementRate": 0.42,
  "bio": "Nat fotógrafa y filmmaker\\n🏔️ Viviendo en Bariloche\\nSeguime en Ig👇🏼",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:36:12.481Z"
},
  {
  "handle": "real777salty",
  "profileUrl": "https://www.tiktok.com/@real777salty",
  "followers": 71900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/real777salty.jpeg",
  "niche": "travel",
  "avgViews": 13584,
  "engagementRate": 4.22,
  "bio": "See life through me 🌁\\nFounder @TradingPool\\nIG: 777salty",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:37:03.136Z"
},
  {
  "handle": "travelwithloz_",
  "profileUrl": "https://www.tiktok.com/@travelwithloz_",
  "followers": 25500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/travelwithloz_.jpeg",
  "niche": "travel",
  "avgViews": 619710,
  "engagementRate": 80.03,
  "bio": "Travelling the world in my 20s 🌞🌸🌴🌊\\nEnquiries ⬇️⬇️",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:37:31.536Z"
},
  {
  "handle": "iam.riss14",
  "profileUrl": "https://www.tiktok.com/@iam.riss14",
  "followers": 35600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/iam.riss14.jpeg",
  "niche": "travel",
  "avgViews": 650385,
  "engagementRate": 250.17,
  "bio": "id cacput : iamriss \\npinterest, pexels",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:38:21.969Z"
},
  {
  "handle": "iheartnewyorkcityy",
  "profileUrl": "https://www.tiktok.com/@iheartnewyorkcityy",
  "followers": 71400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/iheartnewyorkcityy.jpeg",
  "niche": "travel",
  "avgViews": 1738639,
  "engagementRate": 321.72,
  "bio": "✨🍵🪷🤍\\n\\nmoodboards\\n\\n pinterest: @iheartnewyorkcityy",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:39:28.349Z"
},
  {
  "handle": "quincy.visuals",
  "profileUrl": "https://www.tiktok.com/@quincy.visuals",
  "followers": 49200,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/quincy.visuals.jpeg",
  "niche": "travel",
  "avgViews": 401419,
  "engagementRate": 95.45,
  "bio": "Aesthetic - Cinematic\\nCC ID:8744089034\\nFor work: quyenphamdue@gmail.com",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:40:07.058Z"
},
  {
  "handle": "oroobameera",
  "profileUrl": "https://www.tiktok.com/@oroobameera",
  "followers": 19500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/oroobameera.jpeg",
  "niche": "travel",
  "avgViews": 27383,
  "engagementRate": 4.12,
  "bio": "𝑐𝑎𝑛𝑜𝑛 𝑝ℎ𝑜𝑡𝑜𝑔𝑟𝑎𝑔ℎ𝑦📸",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:41:00.141Z"
},
  {
  "handle": "greenfx.world",
  "profileUrl": "https://www.tiktok.com/@greenfx.world",
  "followers": 57500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/greenfx.world.jpeg",
  "niche": "travel",
  "avgViews": 602625,
  "engagementRate": 21.26,
  "bio": "I Want To Explore The Beauty Of World ♥️🥀",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:45:04.264Z"
},
  {
  "handle": "trip.tailors",
  "profileUrl": "https://www.tiktok.com/@trip.tailors",
  "followers": 28300,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/trip.tailors.jpeg",
  "niche": "travel",
  "avgViews": 669153,
  "engagementRate": 205.65,
  "bio": "Tailored Travel 🐳☀️\\n\\nGet your vacation planned by experts✈️\\n⬇️",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:46:06.530Z"
},
  {
  "handle": "madladsaf",
  "profileUrl": "https://www.tiktok.com/@madladsaf",
  "followers": 37600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/madladsaf.jpeg",
  "niche": "travel",
  "avgViews": 10531,
  "engagementRate": 1.57,
  "bio": "Saf\\n📍London\\nCars 🚙 Travel ✈️",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:46:47.593Z"
},
  {
  "handle": "uzma.mahbub",
  "profileUrl": "https://www.tiktok.com/@uzma.mahbub",
  "followers": 12300,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/uzma.mahbub.jpeg",
  "niche": "travel",
  "avgViews": 789117,
  "engagementRate": 857.63,
  "bio": "travel • london • lifestyle\\n✈️🌍🌅🦒",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:47:17.134Z"
},
  {
  "handle": "caminievar",
  "profileUrl": "https://www.tiktok.com/@caminievar",
  "followers": 19600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/caminievar.jpeg",
  "niche": "travel",
  "avgViews": 19519,
  "engagementRate": 5.99,
  "bio": "mi diario visual ☁️\\n💌 camilanievaph@gmail.com",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:48:13.925Z"
},
  {
  "handle": "lifewithelliott",
  "profileUrl": "https://www.tiktok.com/@lifewithelliott",
  "followers": 12700,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/lifewithelliott.jpeg",
  "niche": "travel",
  "avgViews": 557179,
  "engagementRate": 599.85,
  "bio": "Travel photographer 📸🗺️\\n71 countries\\nFollow on IG for more travel inspo 😊👇",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:49:00.970Z"
},
  {
  "handle": "barbiesook",
  "profileUrl": "https://www.tiktok.com/@barbiesook",
  "followers": 11400,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/barbiesook.jpeg",
  "niche": "makeup",
  "avgViews": 612,
  "engagementRate": 0.4,
  "bio": "https:\\u002F\\u002Fwww.instagram.com\\u002Fbarbiesok\\u002F?hl=es 🤍",
  "country": "por",
  "lastScrapedAt": "2025-09-19T08:49:45.208Z"
},
  {
  "handle": "macarr.on",
  "profileUrl": "https://www.tiktok.com/@macarr.on",
  "followers": 10800,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/macarr.on.jpeg",
  "niche": "travel",
  "avgViews": 6147,
  "engagementRate": 4.94,
  "bio": "Cositas varias 🙂⚡️",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:50:40.980Z"
},
  {
  "handle": "katherinee.vega",
  "profileUrl": "https://www.tiktok.com/@katherinee.vega",
  "followers": 19900,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/katherinee.vega.jpeg",
  "niche": "travel",
  "avgViews": 8991,
  "engagementRate": 3.72,
  "bio": "🇪🇨 | 🇪🇸",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:52:29.595Z"
},
  {
  "handle": "destinoliviano",
  "profileUrl": "https://www.tiktok.com/@destinoliviano",
  "followers": 15500,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/destinoliviano.jpeg",
  "niche": "travel",
  "avgViews": 456439,
  "engagementRate": 284.33,
  "bio": "Instagram: DestinoLiviano\\n💌 destinoliviano@gmail.com",
  "country": "spa",
  "lastScrapedAt": "2025-09-19T08:53:25.845Z"
},
  {
  "handle": "iranaretzz",
  "profileUrl": "https://www.tiktok.com/@iranaretzz",
  "followers": 60600,
  "avatarUrl": "https://tiktokfinder.onrender.com/avatars/iranaretzz.jpeg",
  "niche": "travel",
  "avgViews": 2643,
  "engagementRate": 0.19,
  "bio": "Thank you ❤️\\n🌸🌸🌸🌸🌸🌸🌸🌸🌸🌸🌸",
  "country": "eng",
  "lastScrapedAt": "2025-09-19T08:54:21.170Z"
},
];

async function main() {
  for (const tiktoker of tiktokers) {
    await prisma.tiktoker.upsert({
      where: { handle: tiktoker.handle },
      update: tiktoker,
      create: tiktoker,
    });
  }
}

main()
  .then(() => {
    console.log("✅ Seed completado");
    return prisma.$disconnect();
  })
  .catch((e) => {
    console.error("❌ Error al hacer seed:", e);
    return prisma.$disconnect();
  });
